import { LangCode } from "./LanguageContext";

export type TranslationKey =
  | "nav.home" | "nav.work" | "nav.services" | "nav.about" | "nav.contact" | "nav.startProject" | "nav.bookCall"
  | "hero.badge" | "hero.location" | "hero.headline" | "hero.subheadline" | "hero.cta.primary" | "hero.cta.secondary" | "hero.proof"
  | "home.mockup.fash.studio" | "home.mockup.fash.drop" | "home.mockup.fash.remaining" | "home.mockup.fash.price" | "home.mockup.fash.reserve"
  | "home.mockup.mcc.badge" | "home.mockup.mcc.status" | "home.mockup.mcc.title" | "home.mockup.mcc.token" | "home.mockup.mcc.session" | "home.mockup.mcc.monitoring"
  | "home.mockup.seq.badge" | "home.mockup.seq.growth" | "home.mockup.seq.batch" | "home.mockup.seq.amount"
  | "home.mockup.telemetry.badge" | "home.mockup.telemetry.uptime" | "home.mockup.telemetry.flutter" | "home.mockup.telemetry.api" | "home.mockup.telemetry.cold" | "home.mockup.telemetry.fps"
  | "manifesto.label" | "manifesto.sectionTitle" | "manifesto.headline" | "manifesto.body"
  | "capabilities.label" | "capabilities.title" | "capabilities.subtitle"
  | "capabilities.1.title" | "capabilities.1.desc" | "capabilities.1.badge"
  | "capabilities.2.title" | "capabilities.2.desc"
  | "capabilities.3.title" | "capabilities.3.desc"
  | "capabilities.4.title" | "capabilities.4.desc"
  | "capabilities.5.title" | "capabilities.5.desc"
  | "portfolio.label" | "portfolio.title"
  | "portfolio.seq.badge1" | "portfolio.seq.badge2" | "portfolio.seq.badge3" | "portfolio.seq.num" | "portfolio.seq.title" | "portfolio.seq.sub" | "portfolio.seq.desc" | "portfolio.seq.stat1v" | "portfolio.seq.stat1l" | "portfolio.seq.stat2v" | "portfolio.seq.stat2l" | "portfolio.seq.stat3v" | "portfolio.seq.stat3l" | "portfolio.seq.status"
  | "portfolio.fash.badge1" | "portfolio.fash.badge2" | "portfolio.fash.badge3" | "portfolio.fash.num" | "portfolio.fash.title" | "portfolio.fash.sub" | "portfolio.fash.desc" | "portfolio.fash.stat1v" | "portfolio.fash.stat1l" | "portfolio.fash.stat2v" | "portfolio.fash.stat2l" | "portfolio.fash.stat3v" | "portfolio.fash.stat3l"
  | "testimonials.label" | "testimonials.title"
  | "testimonials.1.quote" | "testimonials.1.name" | "testimonials.1.role"
  | "testimonials.2.quote" | "testimonials.2.name" | "testimonials.2.role"
  | "whoWeAre.label" | "whoWeAre.title" | "whoWeAre.body"
  | "whoWeAre.stat1v" | "whoWeAre.stat1l" | "whoWeAre.stat2v" | "whoWeAre.stat2l" | "whoWeAre.stat3v" | "whoWeAre.stat3l" | "whoWeAre.stat4v" | "whoWeAre.stat4l"
  | "faq.label" | "faq.title"
  | "inquiry.label" | "inquiry.title" | "inquiry.body" | "inquiry.cta" | "inquiry.check1" | "inquiry.check2"
  | "footer.tagline" | "footer.location" | "footer.privacy" | "footer.terms" | "footer.security" | "footer.rights"
  | "services.label" | "services.title" | "services.subtitle"
  | "work.label" | "work.title" | "work.subtitle" | "work.viewAll"
  | "about.label" | "about.title" | "about.subtitle"
  | "contact.label" | "contact.title" | "contact.subtitle"
  | "common.readMore" | "common.learnMore" | "common.getInTouch" | "common.viewCaseStudy"
  | "about.mandate.badge" | "about.mandate.loc1" | "about.mandate.loc2" | "about.mandate.loc3" | "about.mandate.label" | "about.mandate.title" | "about.mandate.p1" | "about.mandate.p2"
  | "about.stats.1.label" | "about.stats.2.label" | "about.stats.3.label" | "about.stats.4.label"
  | "about.principles.label" | "about.principles.title"
  | "about.principles.1.title" | "about.principles.1.desc" | "about.principles.1.check1" | "about.principles.1.check2" | "about.principles.1.check3"
  | "about.principles.2.title" | "about.principles.2.desc" | "about.principles.2.check1" | "about.principles.2.check2" | "about.principles.2.check3"
  | "about.principles.3.title" | "about.principles.3.desc" | "about.principles.3.check1" | "about.principles.3.check2" | "about.principles.3.check3"
  | "about.hubs.label" | "about.hubs.title" | "about.hubs.desc"
  | "about.hubs.1.badge" | "about.hubs.1.location" | "about.hubs.1.title" | "about.hubs.1.desc" | "about.hubs.1.tz" | "about.hubs.1.radius"
  | "about.hubs.2.badge" | "about.hubs.2.location" | "about.hubs.2.title" | "about.hubs.2.desc" | "about.hubs.2.tz" | "about.hubs.2.radius"
  | "about.partners.label"
  | "contact.hero.f1" | "contact.hero.f2" | "contact.hero.f3"
  | "contact.sidebar.discovery" | "contact.sidebar.discovery.title" | "contact.sidebar.discovery.desc"
  | "contact.sidebar.email.label" | "contact.sidebar.phone.label"
  | "contact.sidebar.wa.title" | "contact.sidebar.wa.badge" | "contact.sidebar.wa.desc"
  | "contact.sidebar.ops.label" | "contact.sidebar.ops.1.title" | "contact.sidebar.ops.1.addr" | "contact.sidebar.ops.2.title" | "contact.sidebar.ops.2.addr"
  | "contact.sidebar.nda.title" | "contact.sidebar.nda.desc"
  | "contact.protocol.label" | "contact.protocol.title" | "contact.protocol.desc"
  | "contact.protocol.1.badge" | "contact.protocol.1.title" | "contact.protocol.1.desc"
  | "contact.protocol.1.badge" | "contact.protocol.1.title" | "contact.protocol.1.desc"
  | "contact.protocol.2.badge" | "contact.protocol.2.title" | "contact.protocol.2.desc"
  | "contact.protocol.3.badge" | "contact.protocol.3.title" | "contact.protocol.3.desc"
  | "portfolio.mcc.badge1" | "portfolio.mcc.badge2" | "portfolio.mcc.badge3" | "portfolio.mcc.badge4" | "portfolio.mcc.num" | "portfolio.mcc.title" | "portfolio.mcc.sub" | "portfolio.mcc.desc" | "portfolio.mcc.stat1v" | "portfolio.mcc.stat1l" | "portfolio.mcc.stat2v" | "portfolio.mcc.stat2l" | "portfolio.mcc.stat3v" | "portfolio.mcc.stat3l" | "portfolio.mcc.status" | "portfolio.fash.status"
  | "work.hero.badge" | "work.hero.tag1" | "work.hero.tag2" | "work.hero.tag3" | "work.caseStudy" | "work.appStore" | "work.cta.badge"
  | "nav.privacy" | "nav.terms" | "nav.security"
  | "legal.privacy.title" | "legal.privacy.date" | "legal.privacy.s1" | "legal.privacy.p1" | "legal.privacy.s2" | "legal.privacy.p2"
  | "legal.terms.title" | "legal.terms.date" | "legal.terms.s1" | "legal.terms.p1" | "legal.terms.s2" | "legal.terms.p2"
  | "legal.security.title" | "legal.security.date" | "legal.security.s1" | "legal.security.p1" | "legal.security.s2" | "legal.security.p2"
  | "services.hero.badge" | "services.hero.tag1" | "services.hero.tag2" | "services.hero.tag3"
  | "services.build.badge" | "services.build.title" | "services.build.desc"
  | "services.build.f.badge" | "services.build.f.title" | "services.build.f.desc"
  | "services.build.f.p1.t" | "services.build.f.p1.d"
  | "services.build.f.p2.t" | "services.build.f.p2.d"
  | "services.build.f.p3.t" | "services.build.f.p3.d"
  | "services.build.f.tag1" | "services.build.f.tag2" | "services.build.f.tag3"
  | "services.build.1.num" | "services.build.1.title" | "services.build.1.desc"
  | "services.build.2.num" | "services.build.2.title" | "services.build.2.desc"
  | "services.build.3.num" | "services.build.3.title" | "services.build.3.desc"
  | "services.build.4.num" | "services.build.4.title" | "services.build.4.desc"
  | "seo.home.title" | "seo.home.desc" | "seo.about.title" | "seo.about.desc"
  | "seo.services.title" | "seo.services.desc" | "seo.work.title" | "seo.work.desc";

type Translations = Partial<Record<TranslationKey, string>>;
type AllTranslations = Partial<Record<LangCode, Translations>>;

export const translations: AllTranslations = {
  ar: {
    "seo.home.title": "شركة تطوير تطبيقات الجوال في الكويت والخليج | Avenore Tech",
    "seo.home.desc": "نبني تطبيقات فلاتر (Flutter) ومنتجات رقمية عالية الأداء للشركات الناشئة والمؤسسات في الكويت ومنطقة الخليج. هندسة برمجيات موثوقة.",
    "seo.about.title": "أفضل شركة هندسة برمجيات في الكويت | من نحن",
    "seo.about.desc": "تعرف على خبراء هندسة تطبيقات الموبايل في Avenore Tech. فريق متخصص في تصميم وبرمجة التطبيقات الأصلية المتوافقة مع معايير الخليج.",
    "seo.services.title": "خدمات برمجة وتصميم التطبيقات (iOS/Android) | Avenore Tech",
    "seo.services.desc": "نقدم خدمات تطوير تطبيقات الموبايل باستخدام تقنيات Flutter، وتطوير البنية التحتية السحابية (Backend) وحلول الدفع مثل K-NET لأسواق الخليج.",
    "seo.work.title": "أعمالنا في تطوير التطبيقات والبرمجيات في الخليج",
    "seo.work.desc": "استعرض سابقة أعمالنا في تطوير تطبيقات الموبايل والمتاجر الإلكترونية للشركات الناشئة والمؤسسات الحكومية في الكويت والإمارات.",
    "nav.home": "الرئيسية", "nav.work": "أعمالنا", "nav.services": "خدماتنا", "nav.about": "من نحن", "nav.contact": "تواصل معنا", "nav.startProject": "ابدأ مشروعك", "nav.bookCall": "احجز مكالمة",
    "hero.badge": "استوديو هندسة البرمجيات · تأسس 2026", "hero.location": "تطوير تطبيقات الجوال · الكويت والخليج", "hero.headline": "نبني تطبيقات رقمية يتفاعل معها ملايين المستخدمين.", "hero.subheadline": "تطوير تطبيقات الهواتف الذكية (iOS/Android). منتجات رقمية قابلة للتوسع. هندسة برمجيات احترافية. نتشارك مع المؤسسين والشركات الكبرى في الكويت، السعودية، والإمارات.", "hero.cta.primary": "ابدأ مشروعك", "hero.cta.secondary": "استعرض أعمالنا", "hero.proof": "+20 تطبيقاً إنتاجياً تم شحنه لـ FASH وSequifi وMCC دبي",
    "home.mockup.fash.studio": "FASH استوديو", "home.mockup.fash.drop": "إصدار منتقى #12", "home.mockup.fash.remaining": "124 قطعة متبقية", "home.mockup.fash.price": "125.000 د.ك", "home.mockup.fash.reserve": "حجز",
    "home.mockup.mcc.badge": "MCC دبي · موثق", "home.mockup.mcc.status": "متصل", "home.mockup.mcc.title": "دخول الهوية الإماراتية", "home.mockup.mcc.token": "رمز أمان صلب", "home.mockup.mcc.session": "جلسة #99402 موثقة", "home.mockup.mcc.monitoring": "مراقبة 14 قطاعاً",
    "home.mockup.seq.badge": "SEQUIFI · عمولات", "home.mockup.seq.growth": "+18.4%", "home.mockup.seq.batch": "دفعة دفع #409", "home.mockup.seq.amount": "$84,200.00",
    "home.mockup.telemetry.badge": "القياس الأساسي", "home.mockup.telemetry.uptime": "99.99%", "home.mockup.telemetry.flutter": "Flutter Engine", "home.mockup.telemetry.api": "API Latency", "home.mockup.telemetry.cold": "Cold Start", "home.mockup.telemetry.fps": "Frame Render",
    "manifesto.label": "01 / الفكرة", "manifesto.sectionTitle": "فلسفة الاستوديو", "manifesto.headline": "فكرتك تستحق أكثر من مجرد تطبيق.", "manifesto.body": "نهندس منتجات رقمية رائدة وراسخة ببنية Flutter متينة، وتفاعلات دقيقة مبهرة، وموثوقية سحابية بمستوى المؤسسات. لا قوالب مُخصصة، لا طبقات مطورين غير كفؤة — فقط مهندسون كبار يشحنون منتجات تُبقي المستخدمين وتولّد رأس مال حقيقياً.",
    "capabilities.label": "02 / القدرات", "capabilities.title": "ما نبنيه", "capabilities.subtitle": "أنظمة عالية الأداء، ومنظومات موبايل مخصصة، وبنية تحتية موزعة مصممة لتتجاوز تحولات السوق.",
    "capabilities.1.title": "محركات iOS و Android", "capabilities.1.desc": "قواعد بيانات Flutter إنتاجية متينة تنتج فيزياء سلسة بـ 120 إطاراً في الثانية. لا تنازلات هجينة.", "capabilities.1.badge": "تجميع أصلي",
    "capabilities.2.title": "البنية التحتية الخلفية", "capabilities.2.desc": "قواعد PostgreSQL موزعة، WebSockets في الوقت الفعلي، وبنية متوافقة مع دول الخليج بدون توقف.",
    "capabilities.3.title": "تصميم المنتجات", "capabilities.3.desc": "تفاعلات دقيقة ملموسة وواجهات مستخدم جاهزة لاتجاه النص من اليمين لليسار (RTL).",
    "capabilities.4.title": "نماذج أولية (MVP)", "capabilities.4.desc": "نماذج أولية مشحونة في 8-12 أسبوعاً لتأمين جولات التمويل المؤسسية.",
    "capabilities.5.title": "لوحات تحكم الويب", "capabilities.5.desc": "سير عمل تشغيلي موحد ولوحات تحكم القياس للتجار في الوقت الفعلي.",
    "portfolio.label": "05 / المحفظة", "portfolio.title": "أعمال مختارة",
    "portfolio.seq.badge1": "الموارد البشرية", "portfolio.seq.badge2": "FLUTTER", "portfolio.seq.badge3": "مبيعات ميدانية", "portfolio.seq.num": "01 / ريادة التكنولوجيا المالية", "portfolio.seq.title": "SEQUIFI", "portfolio.seq.sub": "إدارة العمولات المؤتمتة في الوقت الفعلي والخدمات المصرفية للقوى العاملة", "portfolio.seq.desc": "صُمم SEQUIFI لفرق المبيعات الميدانية عالية السرعة، وهو يستبدل جداول البيانات الهشة بحساب العمولات المؤتمت، والتحقق من فترة الدفع، ولوحات الصدارة المحفزة لأكثر من 8000 مندوب نشط.", "portfolio.seq.stat1v": "+8,000", "portfolio.seq.stat1l": "مندوب نشط", "portfolio.seq.stat2v": "100%", "portfolio.seq.stat2l": "جاهز دون اتصال", "portfolio.seq.stat3v": "+$140M", "portfolio.seq.stat3l": "تدفق الرواتب", "portfolio.seq.status": "إنتاج V4.2.0 • نشط",
    "portfolio.fash.badge1": "سوق أزياء", "portfolio.fash.badge2": "FLUTTER", "portfolio.fash.badge3": "كي-نت", "portfolio.fash.num": "02 // تجارة فاخرة", "portfolio.fash.title": "FASH", "portfolio.fash.sub": "إصدارات عالية التزامن لبوتيكات الكويت والإمارات الفاخرة", "portfolio.fash.desc": "مُصمم لأكثر دور الأزياء انتقائية في المنطقة. يتعامل FASH مع حركة مرور مفاجئة شديدة أثناء الإصدارات المحدودة مع طابور دفع خالٍ من الاحتكاك ومزامنة دفع K-NET متعددة العملات.", "portfolio.fash.stat1v": "<2.1s", "portfolio.fash.stat1l": "تدفق الدفع", "portfolio.fash.stat2v": "+100k", "portfolio.fash.stat2l": "حركة الإصدار", "portfolio.fash.stat3v": "4.9 ★", "portfolio.fash.stat3l": "تقييم المتجر",
    "testimonials.label": "07 / التحقق", "testimonials.title": "آراء عملائنا",
    "testimonials.1.quote": "«أفينور لا تتصرف كمورد خارجي؛ بل كفريق هندسي أساسي لا يساوم. لقد سلموا تطبيق Flutter الكامل في 11 أسبوعًا فقط، وظل معدل الانهيار في الإنتاج صفرًا عبر مئات الآلاف من الجلسات.»", "testimonials.1.name": "ماركوس فانكامب", "testimonials.1.role": "المدير التقني · PayGlide Systems",
    "testimonials.2.quote": "«مستوى براعة التفاعل الدقيق وتصميم الإيماءات الذي جلبوه إلى Sequifi غيّر تمامًا كيفية استخدام ممثلينا لبرامجنا. يتم دفع العمولات بدقة وقفزت مقاييس الاحتفاظ بالعملاء بنسبة 32% خلال 60 يومًا من الإطلاق.»", "testimonials.2.name": "بريا رامان", "testimonials.2.role": "رئيسة المنتجات · Sequifi",
    "whoWeAre.label": "08 / من نحن", "whoWeAre.title": "نهتم بما يحدث بعد الإطلاق.", "whoWeAre.body": "تأسسنا على مبدأ أن يوم الإطلاق هو خط البداية. نشحن تطبيقات إنتاجية متينة مع موثوقية مواقع على مدار الساعة وحرفة هندسية مبهرة للمؤسسين الذين يطالبون بمنتجات تُعرّف فئتها.",
    "whoWeAre.stat1v": "+20", "whoWeAre.stat1l": "تطبيق تم شحنه", "whoWeAre.stat2v": "100%", "whoWeAre.stat2l": "دقة Flutter", "whoWeAre.stat3v": "+8", "whoWeAre.stat3l": "أسواق عالمية", "whoWeAre.stat4v": "+5", "whoWeAre.stat4l": "سنوات خبرة",
    "faq.label": "استفسارات", "faq.title": "الأسئلة الشائعة",
    "inquiry.label": "طلب مشروع", "inquiry.title": "هل لديك شيء يستحق البناء؟", "inquiry.body": "دعنا نتحدث عنه. أخبرنا عن جدولك الزمني وقيود المنتج وطموحاتك في السوق. نرد بتقديرات معمارية في أقل من 24 ساعة.", "inquiry.cta": "احجز مكالمة اكتشاف سريعة →", "inquiry.check1": "توقيع اتفاقية سرية (NDA) قبل أي نقاش", "inquiry.check2": "محادثة مباشرة مع مهندس المنتج الرئيسي",
    "footer.tagline": "نبني منتجات يعود إليها الناس. تطبيقات موبايل. منتجات رقمية. هندسة جادة.", "footer.location": "الكويت · منطقة الخليج · التسليم العالمي", "footer.privacy": "سياسة الخصوصية", "footer.terms": "شروط الخدمة", "footer.security": "الأمان", "footer.rights": "© 2026 أفينور استوديو. جميع الحقوق محفوظة.",
    "services.label": "خدماتنا", "services.title": "هندسة تطبيقات موبايل الكاملة", "services.subtitle": "من Flutter إلى البنية التحتية السحابية — نبني كل طبقة.",
    "work.label": "أعمالنا", "work.title": "أعمال مختارة ودراسات حالة هندسية", "work.subtitle": "تطبيقات موبايل إنتاجية رائدة، وأسواق رقمية، ومنصات مؤسسية عبر الكويت ومنطقة الخليج.", "work.viewAll": "عرض جميع دراسات الحالة",
    "about.label": "من نحن", "about.title": "نهندس منتجاً، وليس مجرد تطبيق.", "about.subtitle": "تأسسنا في الكويت، ونشحن في أسواق الخليج العربي والعالم.",
    "contact.label": "تواصل معنا", "contact.title": "ابدأ مشروعك معنا", "contact.subtitle": "نرد على جميع الاستفسارات في غضون 24 ساعة.",
    "common.readMore": "اقرأ المزيد", "common.learnMore": "تعلم أكثر", "common.getInTouch": "تواصل معنا", "common.viewCaseStudy": "عرض دراسة الحالة",
    "about.mandate.badge": "تفويضنا", "about.mandate.loc1": "المقر الرئيسي: مدينة الكويت", "about.mandate.loc2": "مركز الهندسة في بنغالور", "about.mandate.loc3": "تأسس 2026", "about.mandate.label": "التفويض", "about.mandate.title": "نحن لا نصنع برمجيات للاستعمال مرة واحدة.", "about.mandate.p1": "يتطلب السوق الخليجي منتجات موبايل مصممة للتعامل مع أنظمة الدفع الإقليمية، وواجهات تدعم اللغتين معاً (RTL)، وسيناريوهات الازدحام الشديد خلال مواسم الأعياد. لقد تأسسنا خصيصاً لتلبية ذلك.", "about.mandate.p2": "كل سطر برمجي من Flutter و Swift و Kotlin و Python نطلقه يتم تزويده بأدوات قياس الأداء وتتبع الأعطال، واختباره بالكامل، ومراجعته بواسطة مهندسين كبار شحنوا تطبيقات لملايين المستخدمين.",
    "about.stats.1.label": "تطبيق إنتاجي تم إطلاقه", "about.stats.2.label": "أسواق خليجية نشطة", "about.stats.3.label": "بنية Flutter الأساسية", "about.stats.4.label": "سنوات من الخبرة الهندسية",
    "about.principles.label": "كيف نعمل", "about.principles.title": "ثلاثة مبادئ لا مساومة فيها", 
    "about.principles.1.title": "نشحن المنتج، ثم نبقى", "about.principles.1.desc": "يوم الإطلاق ليس خط النهاية — بل هو بداية العلاقة. نراقب أداء التطبيق، ومراجعات المتاجر، ومسارات التحويل، وتحديثات أنظمة التشغيل باستمرار.", "about.principles.1.check1": "تنبيهات فورية وتحليل مباشر للأعطال", "about.principles.1.check2": "مراجعة أسبوعية للأداء ومعدلات التحويل", "about.principles.1.check3": "تحديث قواعد البيانات دون توقف",
    "about.principles.2.title": "فريق واحد، بلا وسطاء", "about.principles.2.desc": "يكتب المصممون المتغيرات مباشرة في الكود؛ ويفهم مهندسو البرمجيات الفروق الدقيقة للخطوط وتحديات اللغة العربية (RTL). لا وجود لمديري حسابات أو أقسام منعزلة.", "about.principles.2.check1": "تواصل مباشر مع مهندس البرمجيات عبر Slack", "about.principles.2.check2": "استعراض يومي للمستجدات عبر Loom", "about.principles.2.check3": "خطوط عمل موحدة من Figma إلى الكود",
    "about.principles.3.title": "مُصمم ليدوم", "about.principles.3.desc": "نرفض النماذج الأولية المؤقتة. كل سطر برمجي موثق بدقة ومختبر بالكامل ومدعوم بخطوط تكامل ونشر مستمرة (CI/CD).", "about.principles.3.check1": "تغطية اختبارية بنسبة 100% للمنطق الأساسي", "about.principles.3.check2": "نقل كامل للملكية الفكرية ومستودع Git", "about.principles.3.check3": "بنية نموذجية نظيفة تتوافق مع مواصفات ISO",
    "about.hubs.label": "بنية المحور المزدوج", "about.hubs.title": "حضور إقليمي. وتوسع استراتيجي.", "about.hubs.desc": "نعمل عبر محورين متناسقين لتقديم استشارات محلية عالية الجودة مدعومة بتطوير برمجيات نخبوي ومستمر لفرق الشركات الناشئة الإقليمية.", 
    "about.hubs.1.badge": "المقر الرئيسي", "about.hubs.1.location": "مدينة الكويت // شرق", "about.hubs.1.title": "الاستراتيجية الإقليمية واستشارات العملاء", "about.hubs.1.desc": "تفاعل مباشر مع المؤسسين ورؤساء الشركات. إدارة التوافق التنظيمي مع المعايير الإقليمية (البنك المركزي، UAE Pass، ساما السعودية).", "about.hubs.1.tz": "المنطقة الزمنية: GMT+3 (AST)", "about.hubs.1.radius": "نطاق الطيران المباشر: أقل من ساعتين",
    "about.hubs.2.badge": "المحرك الأساسي", "about.hubs.2.location": "بنغالور // إنديراناجار", "about.hubs.2.title": "بنية أساسية مخصصة", "about.hubs.2.desc": "هندسة برمجيات عميقة، بناء واجهات برمجية (API) منخفضة التأخير، وتحسين أداء الموبايل. يختبر فريقنا في بنغالور على أكثر من 40 إعدادًا للأجهزة الفعلية.", "about.hubs.2.tz": "المنطقة الزمنية: GMT+5:30 (IST)", "about.hubs.2.radius": "التقاطع: 6.5 ساعات/يوم",
    "about.partners.label": "موثوقون من قِبل قادة الشركات المدعومة والشركات الخليجية",
    "contact.hero.f1": "بروتوكول NDA أولاً", "contact.hero.f2": "مراجعة معمارية خلال 24 ساعة", "contact.hero.f3": "المقر الرئيسي في الكويت",
    "contact.sidebar.discovery": "مكالمة استكشافية 15 دقيقة · متاح", "contact.sidebar.discovery.title": "تحتاج تقييم تقني فوري؟", "contact.sidebar.discovery.desc": "مكالمة مجانية 15 دقيقة · بدون التزام · تواصل مباشر مع المؤسس والمهندس المعماري الرئيسي",
    "contact.sidebar.email.label": "البريد الإلكتروني الرئيسي للاستشارات المعمارية", "contact.sidebar.phone.label": "خط المقر الرئيسي في الكويت (09:00–18:00 بتوقيت السعودية)",
    "contact.sidebar.wa.title": "مكتب واتساب الفوري", "contact.sidebar.wa.badge": "مُوثّق", "contact.sidebar.wa.desc": "استشارات خليجية فورية متاحة",
    "contact.sidebar.ops.label": "عمليات المحور المزدوج", "contact.sidebar.ops.1.title": "استوديو مدينة الكويت (المقر الرئيسي)", "contact.sidebar.ops.1.addr": "شرق، الحي المالي، شارع الخليج العربي، الكويت", "contact.sidebar.ops.2.title": "مركز الهندسة في بنغالور", "contact.sidebar.ops.2.addr": "شارع 100 قدم، إنديراناجار، بنغالور، الهند",
    "contact.sidebar.nda.title": "بروتوكول NDA أولاً مضمون", "contact.sidebar.nda.desc": "توقيع اتفاقية عدم إفشاء (NDA) قبل أي كشف تقني عميق. ملكية فكرية بنسبة 100٪ للعميل مع تسليم نظيف لرمز المصدر.",
    "contact.protocol.label": "البروتوكول", "contact.protocol.title": "ماذا يحدث بعد إرسال طلبك؟", "contact.protocol.desc": "لا وعود فارغة · ملاحظات هندسية مباشرة",
    "contact.protocol.1.badge": "01 / تدقيق", "contact.protocol.1.title": "مراجعة معمارية خلال 24 ساعة", "contact.protocol.1.desc": "يقوم قادتنا الهندسيون بمراجعة مواصفاتك الفنية وجدوى المنصة ومتطلبات التوافق الخليجية.",
    "contact.protocol.2.badge": "02 / مقترح", "contact.protocol.2.title": "تفصيل سباقات التطوير (Sprints) والتكاليف", "contact.protocol.2.desc": "مقترح ثابت النطاق يوضح تشكيل الفريق، الرسوم المعمارية، وجداول زمنية متوقعة.",
    "contact.protocol.3.badge": "03 / انطلاق", "contact.protocol.3.title": "تسليم المستودع وبدء العمل عبر Slack", "contact.protocol.3.desc": "قناة Slack مشتركة مباشرة مع قائدك التقني المخصص. وتوفير مستودع GitHub خاص، ليبدأ العمل خلال 48 ساعة.",
    "portfolio.mcc.badge1": "خدمات حكومية", "portfolio.mcc.badge2": "FLUTTER", "portfolio.mcc.badge3": "UAE PASS", "portfolio.mcc.badge4": "إدارة الأجهزة (MDM)", "portfolio.mcc.num": "03", "portfolio.mcc.title": "MCC DUBAI", "portfolio.mcc.sub": "مجموعة الفحص الميداني للمهام الحرجة والهوية المشفرة", "portfolio.mcc.desc": "وحدة الفحص الميدانية الرسمية لموظفي بلدية دبي. تدمج المصادقة المشفرة عبر UAE Pass، وتخزين القياسات عن بُعد دون اتصال بالإنترنت، والتحقق البيومتري للأجهزة اللوحية.", "portfolio.mcc.stat1v": "L4", "portfolio.mcc.stat1l": "أمن حكومي", "portfolio.mcc.stat2v": "صفر", "portfolio.mcc.stat2l": "تسريب بيانات", "portfolio.mcc.stat3v": "300ms", "portfolio.mcc.stat3l": "سرعة المصادقة", "portfolio.mcc.status": "AES-256 GCM", "portfolio.fash.status": "محرك المبيعات الخاطفة",
    "work.hero.badge": "دراسات الحالة", "work.hero.tag1": "معدل نشر 100% في الخليج", "work.hero.tag2": "Flutter للمؤسسات", "work.hero.tag3": "متوافق مع البنك المركزي و UAE Pass", "work.caseStudy": "دراسة حالة", "work.appStore": "متجر التطبيقات", "work.cta.badge": "▲ AVENORE للهندسة",
    "nav.privacy": "سياسة الخصوصية", "nav.terms": "شروط الخدمة", "nav.security": "الأمن",
    "legal.privacy.title": "سياسة الخصوصية", "legal.privacy.date": "آخر تحديث: سبتمبر 2026",
    "legal.privacy.s1": "1. جمع البيانات والقياس", "legal.privacy.p1": "كشركة هندسية، تقوم Avenore Tech بجمع بيانات القياس الضرورية فقط لمراقبة أداء التطبيقات. نحن لا نبيع البيانات لأطراف ثالثة.",
    "legal.privacy.s2": "2. سرية العميل (NDA)", "legal.privacy.p2": "جميع الاتصالات ورموز المصدر والملكية الفكرية التي يتم مشاركتها معنا محمية بموجب بروتوكول اتفاقية عدم الإفشاء (NDA).",
    "legal.terms.title": "شروط الخدمة", "legal.terms.date": "آخر تحديث: سبتمبر 2026",
    "legal.terms.s1": "1. التسليمات الهندسية", "legal.terms.p1": "تقدم Avenore Tech خدمات هندسة البرمجيات المخصصة. تخضع جميع التسليمات والجداول الزمنية لبيان العمل (SOW) الموقع.",
    "legal.terms.s2": "2. الملكية الفكرية", "legal.terms.p2": "عند سداد الدفعة النهائية، يتم نقل 100٪ من الملكية الفكرية ومستودعات الأكواد للعميل.",
    "legal.security.title": "الوضع الأمني", "legal.security.date": "آخر تحديث: سبتمبر 2026",
    "legal.security.s1": "1. معايير البنية التحتية", "legal.security.p1": "نحن نصمم حلولاً تتبع الامتثال الصارم في منطقة الخليج، بما في ذلك لوائح البنك المركزي و UAE Pass. تستخدم بنيتنا السحابية معماريات خالية من الثقة (Zero-Trust).",
    "legal.security.s2": "2. أمن التطبيقات", "legal.security.p2": "يخضع كل سطر من التعليمات البرمجية لفحص آلي للثغرات. نستخدم تشفير AES-256 GCM للبيانات في وضع السكون.",
    "services.hero.badge": "بناء · تصميم · توسيع", "services.hero.tag1": "الركيزة 01 — البناء", "services.hero.tag2": "الركيزة 02 — التصميم", "services.hero.tag3": "الركيزة 03 — التوسيع",
    "services.build.badge": "الركيزة 01", "services.build.title": "البناء", "services.build.desc": "هندسة التطبيقات الأصلية عبر المنصات والبنية التحتية الخلفية المبنية على مستوى الإنتاج بنطاق هائل.",
    "services.build.f.badge": "01 / البناء الرئيسي", "services.build.f.title": "تطبيق Flutter عبر المنصات", "services.build.f.desc": "قاعدة بيانات برمجية واحدة تترجم إلى تطبيقات iOS و Android أصلية، وتحقق فيزيائية إيماءات بسرعة 120 إطاراً في الثانية بفضل محرك Impeller.",
    "services.build.f.p1.t": "التسليمات", "services.build.f.p1.d": "مستودع الكود الكامل، CI/CD، تقديم متجر التطبيقات",
    "services.build.f.p2.t": "حزمة التقنيات", "services.build.f.p2.d": "Flutter 3.x, Dart 3, Riverpod, Mason CLI",
    "services.build.f.p3.t": "الدورة والتكلفة", "services.build.f.p3.d": "8-12 أسبوع · من $35,000",
    "services.build.f.tag1": "بوابة كي-نت", "services.build.f.tag2": "مزامنة بدون اتصال", "services.build.f.tag3": "طوبولوجيا عربية RTL",
    "services.build.1.num": "02 / إعادة الهندسة", "services.build.1.title": "هندسة Flutter وإعادة البناء", "services.build.1.desc": "إنقاذ الأنظمة المثقلة بالديون التقنية. هجرة قواعد الأكواد المزدوجة المتشابكة إلى مستودعات Flutter موحدة.",
    "services.build.2.num": "03 / APPLE", "services.build.2.title": "الهندسة الأصلية لنظام iOS و Metal", "services.build.2.desc": "تنفيذ عميق لـ Swift و SwiftUI مع استغلال المحرك العصبي، وتصاريح الهوية، واستنتاج CoreML مباشرة على شريحة A-series.",
    "services.build.3.num": "04 / العتاد", "services.build.3.title": "الهندسة الأصلية لنظام Android", "services.build.3.desc": "تطوير Jetpack Compose المصمم لمهام الشركات الحرجة. إنشاء برامج تشغيل لأجهزة POS وحلول الطابعات الحرارية BLE.",
    "services.build.4.num": "05 / البنية التحتية", "services.build.4.title": "النظم الخلفية والخدمات السحابية", "services.build.4.desc": "معماريات مقاومة للأخطاء وجاهزة لتدفق البيانات الكثيف. خدمات موزعة مبرمجة بواسطة Python FastAPI و Node.js."
  },
  en: {
    "seo.home.title": "Premium Mobile App Development Agency Kuwait & GCC | Avenore Tech",
    "seo.home.desc": "We build production-grade Flutter apps and digital products for enterprise and venture-backed startups across Kuwait, Saudi Arabia, and the UAE.",
    "seo.about.title": "About Our Software Engineering Agency | Avenore Tech",
    "seo.about.desc": "Meet the senior software architects behind Avenore Tech. We build high-performance, scalable mobile ecosystems for the GCC market.",
    "seo.services.title": "Mobile App Development & Cloud Services | Avenore Tech",
    "seo.services.desc": "Custom cross-platform Flutter development, iOS/Android native engineering, and zero-trust cloud infrastructure tailored for the Middle East.",
    "seo.work.title": "Our Mobile App Portfolio & Case Studies | Avenore Tech",
    "seo.work.desc": "Explore our selected engineering case studies, featuring hyper-scale luxury commerce apps and government field compliance platforms.",
    "nav.home": "Home", "nav.work": "Work", "nav.services": "Services", "nav.about": "About", "nav.contact": "Contact", "nav.startProject": "Start a Project", "nav.bookCall": "Book a quick call",
    "hero.badge": "Software Engineering Studio Est. 2026", "hero.location": "Premium Mobile App Development · Kuwait City", "hero.headline": "We engineer mobile apps people actually use.", "hero.subheadline": "Custom iOS & Android development. Digital products. Enterprise-grade infrastructure. We partner with visionary founders and institutional teams across the GCC.", "hero.cta.primary": "Start a Project", "hero.cta.secondary": "Explore Selected Work", "hero.proof": "20+ Production apps shipped for teams at FASH, Sequifi, and MCC Dubai",
    "home.mockup.fash.studio": "FASH STUDIO", "home.mockup.fash.drop": "Curated Drop #12", "home.mockup.fash.remaining": "124 PIECES REMAINING", "home.mockup.fash.price": "KD 125.000", "home.mockup.fash.reserve": "RESERVE",
    "home.mockup.mcc.badge": "MCC DUBAI · VERIFIED", "home.mockup.mcc.status": "ONLINE", "home.mockup.mcc.title": "UAE Pass Access", "home.mockup.mcc.token": "Secure Hardware Token", "home.mockup.mcc.session": "Session #99402 Authenticated", "home.mockup.mcc.monitoring": "Monitoring 14 Sectors",
    "home.mockup.seq.badge": "SEQUIFI · COMMISSIONS", "home.mockup.seq.growth": "+18.4%", "home.mockup.seq.batch": "Payout Batch #409", "home.mockup.seq.amount": "$84,200.00",
    "home.mockup.telemetry.badge": "CORE TELEMETRY", "home.mockup.telemetry.uptime": "99.99%", "home.mockup.telemetry.flutter": "Flutter Engine", "home.mockup.telemetry.api": "API Latency", "home.mockup.telemetry.cold": "Cold Start", "home.mockup.telemetry.fps": "Frame Render",
    "manifesto.label": "01 / THE IDEA", "manifesto.sectionTitle": "Studio Philosophy", "manifesto.headline": "Your idea deserves more than just an app.", "manifesto.body": "We engineer durable digital flagships with bulletproof Flutter architecture, obsessive micro-interactions, and enterprise-grade cloud reliability. No outsourced templates, no bloated junior layers — just senior engineers shipping products that retain users and generate real capital.",
    "capabilities.label": "02 / CAPABILITIES", "capabilities.title": "What we build", "capabilities.subtitle": "Surgically crafted cross-platform systems, custom mobile ecosystems, and distributed infrastructure engineered to outlast market pivots.",
    "capabilities.1.title": "iOS & Android Engines", "capabilities.1.desc": "Production-hardened Flutter codebases outputting 120 FPS fluid physics. No hybrid compromises.", "capabilities.1.badge": "NATIVE COMPILATION",
    "capabilities.2.title": "Backend Infrastructure", "capabilities.2.desc": "Distributed PostgreSQL, real-time WebSockets, and GCC-compliant zero-downtime architecture.",
    "capabilities.3.title": "Product Ergonomics", "capabilities.3.desc": "Tactile micro-animations and RTL-ready mobile interfaces.",
    "capabilities.4.title": "Venture MVPs", "capabilities.4.desc": "Zero-shortcut prototypes shipped in 8–12 weeks to secure institutional seed rounds.",
    "capabilities.5.title": "Web Consoles", "capabilities.5.desc": "Unified operational workflows and real-time merchant telemetry dashboards.",
    "portfolio.label": "05 / PORTFOLIO", "portfolio.title": "Selected work",
    "portfolio.seq.badge1": "HR & PAYROLL", "portfolio.seq.badge2": "FLUTTER", "portfolio.seq.badge3": "FIELD SALES", "portfolio.seq.num": "01 / FINTECH FLAGSHIP", "portfolio.seq.title": "SEQUIFI", "portfolio.seq.sub": "Real-time automated commission management & workforce banking", "portfolio.seq.desc": "Engineered for high-velocity field sales teams, SEQUIFI replaces fragile spreadsheets with automated commission calculation, pay-period verification, and gamified leaderboards for over 8,000 active reps.", "portfolio.seq.stat1v": "8,000+", "portfolio.seq.stat1l": "Active Reps", "portfolio.seq.stat2v": "100%", "portfolio.seq.stat2l": "Offline Ready", "portfolio.seq.stat3v": "$140M+", "portfolio.seq.stat3l": "Payroll Flow", "portfolio.seq.status": "Production V4.2.0 • Active",
    "portfolio.fash.badge1": "FASHION MARKETPLACE", "portfolio.fash.badge2": "FLUTTER", "portfolio.fash.badge3": "K-NET", "portfolio.fash.num": "02 // LUXURY COMMERCE", "portfolio.fash.title": "FASH", "portfolio.fash.sub": "High-concurrency drops for Kuwait & UAE luxury boutiques", "portfolio.fash.desc": "Tailored for the region's most selective fashion houses. FASH handles extreme burst traffic during limited flash drops with a zero-friction checkout queue and multi-currency K-NET payment synchronization.", "portfolio.fash.stat1v": "<2.1s", "portfolio.fash.stat1l": "Checkout Flow", "portfolio.fash.stat2v": "100k+", "portfolio.fash.stat2l": "Drop Traffic", "portfolio.fash.stat3v": "4.9 ★", "portfolio.fash.stat3l": "Store Rating",
    "testimonials.label": "07 / VALIDATION", "testimonials.title": "Client perspectives",
    "testimonials.1.quote": "“Avenore doesn’t act like an external vendor; they act like an uncompromising core engineering team. They delivered our complete Flutter application in 11 weeks flat, and our crash rate in production has remained literally zero.”", "testimonials.1.name": "Marcus Vancamp", "testimonials.1.role": "CTO · PayGlide Systems",
    "testimonials.2.quote": "“The level of micro-interaction craft and gesture design they brought to Sequifi completely transformed how our field reps use our software. Commissions get paid accurately and retention jumped 32% within 60 days.”", "testimonials.2.name": "Priya Raman", "testimonials.2.role": "Head of Product · Sequifi",
    "whoWeAre.label": "08 / WHO WE ARE", "whoWeAre.title": "We care about what happens after launch.", "whoWeAre.body": "Founded on the principle that launch day is a starting line, not a finish line. We ship production-hardened apps with 24/7 site reliability and obsessive engineering craft.",
    "whoWeAre.stat1v": "20+", "whoWeAre.stat1l": "Apps Shipped", "whoWeAre.stat2v": "100%", "whoWeAre.stat2l": "Flutter Precision", "whoWeAre.stat3v": "8+", "whoWeAre.stat3l": "Global Markets", "whoWeAre.stat4v": "5+", "whoWeAre.stat4l": "Years Experience",
    "faq.label": "INQUIRIES", "faq.title": "Frequently asked queries",
    "inquiry.label": "PROJECT INQUIRY", "inquiry.title": "Have something worth building?", "inquiry.body": "Let's talk about it. Tell us about your timeline, product constraints, and market ambitions. We respond with architectural estimates in under 24 hours.", "inquiry.cta": "Book a quick 15-min discovery call →", "inquiry.check1": "NDA signed before any confidential project discussion", "inquiry.check2": "Direct conversation with a lead product architect",
    "footer.tagline": "WE BUILD PRODUCTS PEOPLE COME BACK TO. Mobile apps. Digital products. Serious engineering.", "footer.location": "Kuwait City • GCC Region • Global Delivery", "footer.privacy": "Privacy Policy", "footer.terms": "Terms of Service", "footer.security": "Security", "footer.rights": "© 2026 Avenore Studio. All rights reserved.",
    "services.label": "SERVICES", "services.title": "Full-Stack Mobile App Engineering", "services.subtitle": "From Flutter to cloud infrastructure — we build every layer.",
    "work.label": "PORTFOLIO", "work.title": "Selected Work & Engineering Case Studies", "work.subtitle": "Production mobile flagships, digital marketplaces, and enterprise platforms across Kuwait and the GCC.", "work.viewAll": "View All Case Studies",
    "about.label": "ABOUT", "about.title": "We engineer a product, not just an app.", "about.subtitle": "Founded in Kuwait. Shipping across the GCC and beyond.",
    "contact.label": "CONTACT", "contact.title": "Start your project with us", "contact.subtitle": "We respond to all inquiries within 24 hours.",
    "common.readMore": "Read More", "common.learnMore": "Learn More", "common.getInTouch": "Get in Touch", "common.viewCaseStudy": "View Case Study",
    "about.mandate.badge": "Our Mandate", "about.mandate.loc1": "Kuwait City HQ", "about.mandate.loc2": "Bangalore Engineering Center", "about.mandate.loc3": "Est. 2026", "about.mandate.label": "THE MANDATE", "about.mandate.title": "We don't do throwaway software.", "about.mandate.p1": "The Gulf market demands mobile products engineered to handle regional payment stacks, Arabic RTL dual-language interfaces, and heavy-traffic scenarios during holiday commerce surges. We were built specifically for them.", "about.mandate.p2": "Every line of Flutter, Swift, Kotlin, and Python we deploy is instrumented for crash telemetry, typed end-to-end, covered by integration tests, and reviewed by senior engineers who have shipped apps to millions of users.",
    "about.stats.1.label": "Production Apps Shipped", "about.stats.2.label": "Active GCC Markets", "about.stats.3.label": "Flutter Core Architecture", "about.stats.4.label": "Years of Combined Craft",
    "about.principles.label": "HOW WE OPERATE", "about.principles.title": "Three non-negotiable principles",
    "about.principles.1.title": "We ship, then we stay", "about.principles.1.desc": "Launch day is not the finish line — it is the start of the relationship. We actively monitor crash telemetry, App Store reviews, live conversion funnels, and breaking OS updates.", "about.principles.1.check1": "Real-time SRE alerting & crash profiling", "about.principles.1.check2": "Weekly performance triage & conversion review", "about.principles.1.check3": "Zero-downtime database upgrades",
    "about.principles.2.title": "One team, no hand-offs", "about.principles.2.desc": "Designers write token variables directly into code; software architects understand tactile typography and Arabic RTL nuances. No account reps or telephone games between siloed departments.", "about.principles.2.check1": "Direct software architect access on Slack", "about.principles.2.check2": "Daily asynchronous Loom walk-throughs", "about.principles.2.check3": "Unified Figma-to-code token pipelines",
    "about.principles.3.title": "Built to be maintained", "about.principles.3.desc": "We reject throwaway prototypes. Every line is documented, strictly type-checked, and backed by automated regression tests and deterministic CI/CD pipelines.", "about.principles.3.check1": "100% test coverage for core logic", "about.principles.3.check2": "Full IP and Git repository ownership transfer", "about.principles.3.check3": "Modular clean architecture adhering to ISO specs",
    "about.hubs.label": "THE DUAL-HUB ARCHITECTURE", "about.hubs.title": "Regional Presence. Deterministic Scale.", "about.hubs.desc": "We operate across two coordinated hubs to give regional venture teams high-touch local advisory backed by elite continuous software development.",
    "about.hubs.1.badge": "HEADQUARTERS", "about.hubs.1.location": "KUWAIT CITY // SHARQ", "about.hubs.1.title": "Regional Strategy & Client Advisory", "about.hubs.1.desc": "Direct physical engagement with founders and enterprise heads. Managing regulatory compliance with regional standards (CBK, UAE Pass, Saudi SAMA).", "about.hubs.1.tz": "TIME-ZONE: GMT+3 (AST)", "about.hubs.1.radius": "DIRECT FLIGHT RADIUS: <2 HRS",
    "about.hubs.2.badge": "CORE ENGINE", "about.hubs.2.location": "BANGALORE // INDIRANAGAR", "about.hubs.2.title": "Dedicated Core Architecture", "about.hubs.2.desc": "Deep software craft, low-latency API construction, and mobile performance tuning. Our Bangalore team tests across 40+ physical device configurations.", "about.hubs.2.tz": "TIME-ZONE: GMT+5:30 (IST)", "about.hubs.2.radius": "OVERLAP: 6.5 HRS/DAY",
    "about.partners.label": "TRUSTED BY VENTURE-BACKED LEADERS & GCC ENTERPRISES",
    "contact.hero.f1": "NDA-First Protocol", "contact.hero.f2": "24h Architectural Review", "contact.hero.f3": "Kuwait City HQ",
    "contact.sidebar.discovery": "15-MIN DISCOVERY CALL · OPEN", "contact.sidebar.discovery.title": "Need Immediate Technical Feedback?", "contact.sidebar.discovery.desc": "Free 15-minute call · no commitment · Direct Founder & Lead Architect access",
    "contact.sidebar.email.label": "Primary Architectural Inbox", "contact.sidebar.phone.label": "Kuwait City HQ Line (09:00–18:00 AST)",
    "contact.sidebar.wa.title": "Instant WhatsApp Desk", "contact.sidebar.wa.badge": "VERIFIED", "contact.sidebar.wa.desc": "Realtime GCC Advisory Available",
    "contact.sidebar.ops.label": "Dual Center Operations", "contact.sidebar.ops.1.title": "Kuwait City Studio (HQ)", "contact.sidebar.ops.1.addr": "Sharq, Financial District, Arabian Gulf Street, Kuwait", "contact.sidebar.ops.2.title": "Bangalore Engineering Center", "contact.sidebar.ops.2.addr": "100ft Road, Indiranagar, Bangalore, KA, India",
    "contact.sidebar.nda.title": "NDA-First Protocol Guaranteed", "contact.sidebar.nda.desc": "Mutual NDA executed prior to deep architectural disclosure. 100% Client IP ownership & clean repository transfer.",
    "contact.protocol.label": "THE PROTOCOL", "contact.protocol.title": "What Happens After You Submit?", "contact.protocol.desc": "Zero Fluff · Direct Engineering Feedback",
    "contact.protocol.1.badge": "01 / AUDIT", "contact.protocol.1.title": "24h Architectural Review", "contact.protocol.1.desc": "Our engineering leads audit your technical specifications, platform viability, and GCC compliance constraints.",
    "contact.protocol.2.badge": "02 / PROPOSAL", "contact.protocol.2.title": "Sprint & Cost Breakdown", "contact.protocol.2.desc": "Fixed-scope milestone proposal detailing team composition, architecture diagrams, and predictable sprint windows.",
    "contact.protocol.3.badge": "03 / KICKOFF", "contact.protocol.3.title": "Repository & Slack Kickoff", "contact.protocol.3.desc": "Direct Slack shared channel with your dedicated tech lead. Private GitHub repository provisioned, sprint begins in 48 hours.",
    "portfolio.mcc.badge1": "GOVERNMENT SERVICES", "portfolio.mcc.badge2": "FLUTTER", "portfolio.mcc.badge3": "UAE PASS", "portfolio.mcc.badge4": "ANDROID MDM", "portfolio.mcc.num": "03", "portfolio.mcc.title": "MCC DUBAI", "portfolio.mcc.sub": "Mission-critical field inspection suite & cryptographic identity", "portfolio.mcc.desc": "Official field agent inspection console for Dubai municipal personnel. Integrates cryptographic authentication via UAE Pass, encrypted offline telemetry caching, and biometric hardware verification on ruggedized enterprise tablets.", "portfolio.mcc.stat1v": "L4", "portfolio.mcc.stat1l": "Gov Security", "portfolio.mcc.stat2v": "Zero", "portfolio.mcc.stat2l": "Data Leaks", "portfolio.mcc.stat3v": "300ms", "portfolio.mcc.stat3l": "Auth Speed", "portfolio.mcc.status": "AES-256 GCM", "portfolio.fash.status": "Flash Drop Engine",
    "work.hero.badge": "Case Studies", "work.hero.tag1": "100% GCC Deployment Rate", "work.hero.tag2": "Enterprise Flutter", "work.hero.tag3": "CBK & UAE Pass Compliant", "work.caseStudy": "CASE STUDY", "work.appStore": "App Store", "work.cta.badge": "▲ AVENORE ENGINEERING",
    "nav.privacy": "Privacy Policy", "nav.terms": "Terms of Service", "nav.security": "Security",
    "legal.privacy.title": "Privacy Policy", "legal.privacy.date": "Last Updated: September 2026",
    "legal.privacy.s1": "1. Data Collection & Telemetry", "legal.privacy.p1": "As an engineering firm, Avenore Tech collects only the necessary telemetry data to monitor application health and performance. We do not sell data to third parties.",
    "legal.privacy.s2": "2. Client Confidentiality (NDA)", "legal.privacy.p2": "All communications, source code, and intellectual property shared with us are protected under our NDA-first protocol.",
    "legal.terms.title": "Terms of Service", "legal.terms.date": "Last Updated: September 2026",
    "legal.terms.s1": "1. Engineering Deliverables", "legal.terms.p1": "Avenore Tech provides custom software engineering services. All deliverables, timelines, and milestones are governed by a mutually signed Statement of Work (SOW).",
    "legal.terms.s2": "2. Intellectual Property", "legal.terms.p2": "Upon final payment, 100% of the Intellectual Property (IP) and source code repositories are transferred cleanly to the client.",
    "legal.security.title": "Security Posture", "legal.security.date": "Last Updated: September 2026",
    "legal.security.s1": "1. Infrastructure Standards", "legal.security.p1": "We engineer solutions following strict GCC compliance, including CBK and UAE Pass regulations. Our cloud infrastructure leverages Zero-Trust architectures.",
    "legal.security.s2": "2. Application Security", "legal.security.p2": "Every line of code undergoes automated vulnerability scanning, strict typing, and peer review. We employ AES-256 GCM encryption for data at rest.",
    "services.hero.badge": "Build · Design · Scale", "services.hero.tag1": "PILLAR 01 — BUILD", "services.hero.tag2": "PILLAR 02 — DESIGN", "services.hero.tag3": "PILLAR 03 — SCALE",
    "services.build.badge": "PILLAR 01", "services.build.title": "Build", "services.build.desc": "Cross-platform native engineering and back-end infrastructure built to production-grade at extreme scale.",
    "services.build.f.badge": "01 / FLAGSHIP BUILD", "services.build.f.title": "Cross-Platform Flutter App", "services.build.f.desc": "One deterministic codebase compiling to natively rendered iOS and Android apps achieving 120 FPS gesture physics with the Impeller engine. Engineered with Riverpod state machines and CI/CD automated App Store submission pipelines.",
    "services.build.f.p1.t": "Deliverables", "services.build.f.p1.d": "Full source monorepo, CI/CD, App Store submission",
    "services.build.f.p2.t": "Core Stack", "services.build.f.p2.d": "Flutter 3.x, Dart 3, Riverpod, Mason CLI",
    "services.build.f.p3.t": "Cycle & Entry", "services.build.f.p3.d": "8–12 wks · From $35,000",
    "services.build.f.tag1": "K-NET GATEWAY", "services.build.f.tag2": "OFFLINE-FIRST SYNC", "services.build.f.tag3": "ARABIC RTL TOPOLOGY",
    "services.build.1.num": "02 / RE-ENGINEERING", "services.build.1.title": "Flutter Architecture & Re-engineering", "services.build.1.desc": "Rescuing tech-debt laden systems. Migration of tangled dual-native codebases into clean, single-source Flutter repositories with deterministic test harnesses.",
    "services.build.2.num": "03 / APPLE", "services.build.2.title": "iOS Native & Metal Engineering", "services.build.2.desc": "Deep Swift & SwiftUI execution exploiting Neural Engine, localized PassKit boarding & identity passes, and CoreML inference directly on the A-series silicon.",
    "services.build.3.num": "04 / HARDWARE", "services.build.3.title": "Android Native Engineering", "services.build.3.desc": "Jetpack Compose development tailored for mission-critical enterprise workflows. Custom Android POS peripheral drivers and BLE thermal printer mesh networks.",
    "services.build.4.num": "05 / INFRASTRUCTURE", "services.build.4.title": "Backend & Cloud Systems", "services.build.4.desc": "Fault-tolerant architectures ready for hyper-traffic surges. Distributed services engineered in Python FastAPI and Node.js, GCC sovereign data residency compliance."
  },
  de: {
    "nav.home": "Startseite", "nav.work": "Referenzen", "nav.services": "Leistungen", "nav.about": "Über uns", "nav.contact": "Kontakt", "nav.startProject": "Projekt starten", "nav.bookCall": "Termin buchen",
    "hero.badge": "Studio Gegr. 2026", "hero.location": "Premium Mobile Apps · Kuwait-Stadt", "hero.headline": "Wir bauen Produkte, zu denen Nutzer zurückkehren.", "hero.subheadline": "Mobile Apps. Digitale Produkte. Ernsthaftes Engineering. Wir arbeiten mit visionären Gründern in der GCC-Region und weltweit zusammen.", "hero.cta.primary": "Projekt starten", "hero.cta.secondary": "Ausgewählte Arbeiten", "hero.proof": "20+ Live-Apps für FASH, Sequifi und MCC Dubai entwickelt",
    "home.mockup.fash.studio": "FASH STUDIO", "home.mockup.fash.drop": "Exklusiver Drop #12", "home.mockup.fash.remaining": "124 STÜCK VERFÜGBAR", "home.mockup.fash.price": "125.000 KD", "home.mockup.fash.reserve": "RESERVIEREN",
    "home.mockup.mcc.badge": "MCC DUBAI · VERIFIZIERT", "home.mockup.mcc.status": "ONLINE", "home.mockup.mcc.title": "UAE Pass Zugang", "home.mockup.mcc.token": "Sicherer Hardware-Token", "home.mockup.mcc.session": "Sitzung #99402 Authentifiziert", "home.mockup.mcc.monitoring": "Überwachung von 14 Sektoren",
    "home.mockup.seq.badge": "SEQUIFI · PROVISIONEN", "home.mockup.seq.growth": "+18.4%", "home.mockup.seq.batch": "Auszahlungslauf #409", "home.mockup.seq.amount": "$84.200,00",
    "home.mockup.telemetry.badge": "KERNTELEMETRIE", "home.mockup.telemetry.uptime": "99.99%", "home.mockup.telemetry.flutter": "Flutter Engine", "home.mockup.telemetry.api": "API Latenz", "home.mockup.telemetry.cold": "Kaltstart", "home.mockup.telemetry.fps": "Bilder/Sek.",
    "manifesto.label": "01 / DIE IDEE", "manifesto.sectionTitle": "Studio-Philosophie", "manifesto.headline": "Ihre Idee verdient mehr als nur eine App.", "manifesto.body": "Wir entwickeln langlebige digitale Flaggschiffe mit robuster Flutter-Architektur, perfektionierten Mikro-Interaktionen und Cloud-Zuverlässigkeit auf Unternehmensniveau. Keine Vorlagen, keine aufgeblähten Teams – nur erfahrene Ingenieure, die Produkte liefern, welche Nutzer binden.",
    "capabilities.label": "02 / KOMPETENZEN", "capabilities.title": "Was wir entwickeln", "capabilities.subtitle": "Plattformübergreifende Systeme, maßgeschneiderte mobile Ökosysteme und skalierbare Infrastrukturen.",
    "capabilities.1.title": "iOS & Android Engines", "capabilities.1.desc": "Produktionsreife Flutter-Codebasen mit 120 FPS Flüssigkeit. Keine Kompromisse bei hybriden Apps.", "capabilities.1.badge": "NATIVE KOMPILIERUNG",
    "capabilities.2.title": "Backend-Infrastruktur", "capabilities.2.desc": "Verteilte PostgreSQL-Datenbanken, Echtzeit-WebSockets und Zero-Downtime-Architektur.",
    "capabilities.3.title": "Produkt-Ergonomie", "capabilities.3.desc": "Taktile Mikro-Animationen und RTL-kompatible Benutzeroberflächen.",
    "capabilities.4.title": "Venture MVPs", "capabilities.4.desc": "Kompromisslose Prototypen in 8–12 Wochen zur Sicherung institutioneller Seed-Runden.",
    "capabilities.5.title": "Web-Konsolen", "capabilities.5.desc": "Vereinheitlichte operative Workflows und Echtzeit-Dashboards für Händler.",
    "portfolio.label": "05 / PORTFOLIO", "portfolio.title": "Ausgewählte Arbeiten",
    "portfolio.seq.badge1": "HR & PAYROLL", "portfolio.seq.badge2": "FLUTTER", "portfolio.seq.badge3": "VERTRIEB", "portfolio.seq.num": "01 / FINTECH FLAGGSCHIFF", "portfolio.seq.title": "SEQUIFI", "portfolio.seq.sub": "Automatisierte Provisionsverwaltung & Banking in Echtzeit", "portfolio.seq.desc": "Speziell für Vertriebsteams entwickelt, ersetzt SEQUIFI Tabellen durch automatisierte Berechnungen, Verifizierungen und Bestenlisten für über 8.000 aktive Nutzer.", "portfolio.seq.stat1v": "8.000+", "portfolio.seq.stat1l": "Aktive Nutzer", "portfolio.seq.stat2v": "100%", "portfolio.seq.stat2l": "Offline bereit", "portfolio.seq.stat3v": "$140M+", "portfolio.seq.stat3l": "Gehaltsvolumen", "portfolio.seq.status": "Produktion V4.2.0 • Aktiv",
    "portfolio.fash.badge1": "FASHION MARKTPLATZ", "portfolio.fash.badge2": "FLUTTER", "portfolio.fash.badge3": "K-NET", "portfolio.fash.num": "02 // LUXUS COMMERCE", "portfolio.fash.title": "FASH", "portfolio.fash.sub": "High-Concurrency Drops für Luxusboutiquen", "portfolio.fash.desc": "Maßgeschneidert für die exklusivsten Modehäuser. FASH bewältigt extreme Lastspitzen mit warteschlangenfreiem Checkout und K-NET-Zahlungssynchronisierung.", "portfolio.fash.stat1v": "<2.1s", "portfolio.fash.stat1l": "Checkout-Zeit", "portfolio.fash.stat2v": "100k+", "portfolio.fash.stat2l": "Drop Traffic", "portfolio.fash.stat3v": "4.9 ★", "portfolio.fash.stat3l": "App Store Rating",
    "testimonials.label": "07 / VALIDIERUNG", "testimonials.title": "Kundenstimmen",
    "testimonials.1.quote": "„Avenore agiert nicht wie ein externer Dienstleister, sondern wie ein Kern-Entwicklungsteam. Sie haben unsere komplette Flutter-Anwendung in 11 Wochen geliefert, und unsere Absturzrate in der Produktion blieb praktisch null.“", "testimonials.1.name": "Marcus Vancamp", "testimonials.1.role": "CTO · PayGlide Systems",
    "testimonials.2.quote": "„Das Niveau der Mikro-Interaktionen und das Design haben die Nutzung unserer Software komplett verändert. Provisionen werden genau abgerechnet und die Bindung stieg innerhalb von 60 Tagen um 32%.“", "testimonials.2.name": "Priya Raman", "testimonials.2.role": "Head of Product · Sequifi",
    "whoWeAre.label": "08 / ÜBER UNS", "whoWeAre.title": "Uns ist wichtig, was nach dem Launch passiert.", "whoWeAre.body": "Wir glauben, dass der Launch nur der Anfang ist. Wir liefern skalierbare, ausfallsichere Apps mit höchster Zuverlässigkeit und bester Entwicklerqualität.",
    "whoWeAre.stat1v": "20+", "whoWeAre.stat1l": "Live-Apps", "whoWeAre.stat2v": "100%", "whoWeAre.stat2l": "Flutter Präzision", "whoWeAre.stat3v": "8+", "whoWeAre.stat3l": "Globale Märkte", "whoWeAre.stat4v": "5+", "whoWeAre.stat4l": "Jahre Erfahrung",
    "faq.label": "ANFRAGEN", "faq.title": "Häufige Fragen",
    "inquiry.label": "PROJEKTANFRAGE", "inquiry.title": "Planen Sie ein neues Projekt?", "inquiry.body": "Lassen Sie uns darüber sprechen. Nennen Sie uns Ihren Zeitplan und Ihre Ziele. Wir antworten innerhalb von 24 Stunden mit Architektur-Schätzungen.", "inquiry.cta": "15-Min. Erstgespräch buchen →", "inquiry.check1": "NDA vor vertraulichen Gesprächen", "inquiry.check2": "Direkter Kontakt zum Lead Architect",
    "footer.tagline": "WIR BAUEN PRODUKTE, ZU DENEN NUTZER ZURÜCKKEHREN. Mobile Apps. Digitale Produkte. Ernsthaftes Engineering.", "footer.location": "Kuwait-Stadt • GCC-Region • Globale Auslieferung", "footer.privacy": "Datenschutz", "footer.terms": "AGB", "footer.security": "Sicherheit", "footer.rights": "© 2026 Avenore Studio. Alle Rechte vorbehalten.",
    "services.label": "LEISTUNGEN", "services.title": "Full-Stack Mobile App Engineering", "services.subtitle": "Von Flutter bis zur Cloud-Infrastruktur — wir bauen jede Schicht.",
    "work.label": "PORTFOLIO", "work.title": "Ausgewählte Fallstudien", "work.subtitle": "Digitale Marktplätze und Unternehmensplattformen für Kuwait und die GCC-Region.", "work.viewAll": "Alle Referenzen ansehen",
    "about.label": "ÜBER UNS", "about.title": "Wir entwickeln ein Produkt, nicht nur eine App.", "about.subtitle": "Gegründet in Kuwait. Weltweit im Einsatz.",
    "contact.label": "KONTAKT", "contact.title": "Starten Sie Ihr Projekt", "contact.subtitle": "Wir antworten auf alle Anfragen innerhalb von 24 Stunden.",
    "common.readMore": "Mehr erfahren", "common.learnMore": "Mehr erfahren", "common.getInTouch": "Kontakt aufnehmen", "common.viewCaseStudy": "Fallstudie ansehen"
  },
  fr: {
    "nav.home": "Accueil", "nav.work": "Réalisations", "nav.services": "Services", "nav.about": "À propos", "nav.contact": "Contact", "nav.startProject": "Démarrer un projet", "nav.bookCall": "Prendre rendez-vous",
    "hero.badge": "Studio fondé en 2026", "hero.location": "Applications mobiles Premium · Koweït", "hero.headline": "Nous créons des produits auxquels les gens reviennent.", "hero.subheadline": "Applications mobiles. Produits digitaux. Ingénierie rigoureuse. Nous collaborons avec des fondateurs visionnaires et des entreprises au CCG et au-delà.", "hero.cta.primary": "Démarrer un projet", "hero.cta.secondary": "Explorer nos réalisations", "hero.proof": "Plus de 20 apps en production pour FASH, Sequifi et MCC Dubaï",
    "home.mockup.fash.studio": "STUDIO FASH", "home.mockup.fash.drop": "Drop exclusif #12", "home.mockup.fash.remaining": "124 PIÈCES RESTANTES", "home.mockup.fash.price": "125.000 KD", "home.mockup.fash.reserve": "RÉSERVER",
    "home.mockup.mcc.badge": "MCC DUBAÏ · VÉRIFIÉ", "home.mockup.mcc.status": "EN LIGNE", "home.mockup.mcc.title": "Accès UAE Pass", "home.mockup.mcc.token": "Jeton matériel sécurisé", "home.mockup.mcc.session": "Session #99402 Authentifiée", "home.mockup.mcc.monitoring": "Surveillance de 14 secteurs",
    "home.mockup.seq.badge": "SEQUIFI · COMMISSIONS", "home.mockup.seq.growth": "+18.4%", "home.mockup.seq.batch": "Paiement lot #409", "home.mockup.seq.amount": "84 200,00 $",
    "home.mockup.telemetry.badge": "TÉLÉMÉTRIE", "home.mockup.telemetry.uptime": "99.99%", "home.mockup.telemetry.flutter": "Moteur Flutter", "home.mockup.telemetry.api": "Latence API", "home.mockup.telemetry.cold": "Démarrage à froid", "home.mockup.telemetry.fps": "Images/sec",
    "manifesto.label": "01 / L'IDÉE", "manifesto.sectionTitle": "Philosophie du studio", "manifesto.headline": "Votre idée mérite plus qu'une simple application.", "manifesto.body": "Nous concevons des fleurons numériques avec une architecture Flutter robuste, des micro-interactions soignées et une infrastructure cloud d'entreprise. Pas de sous-traitance ni d'intermédiaires, seulement des ingénieurs experts qui créent des produits générant des revenus.",
    "capabilities.label": "02 / CAPACITÉS", "capabilities.title": "Ce que nous construisons", "capabilities.subtitle": "Des systèmes multiplateformes chirurgicaux, des écosystèmes mobiles sur mesure et des infrastructures distribuées.",
    "capabilities.1.title": "Moteurs iOS & Android", "capabilities.1.desc": "Codebase Flutter optimisée pour la production avec une fluidité de 120 FPS. Aucun compromis hybride.", "capabilities.1.badge": "COMPILATION NATIVE",
    "capabilities.2.title": "Infrastructure Backend", "capabilities.2.desc": "PostgreSQL distribué, WebSockets en temps réel et architecture sans temps d'arrêt conforme aux normes CCG.",
    "capabilities.3.title": "Ergonomie produit", "capabilities.3.desc": "Micro-animations tactiles et interfaces prêtes pour RTL.",
    "capabilities.4.title": "MVP Startups", "capabilities.4.desc": "Des prototypes fonctionnels livrés en 8 à 12 semaines pour sécuriser des levées de fonds.",
    "capabilities.5.title": "Consoles Web", "capabilities.5.desc": "Outils de gestion unifiés et tableaux de bord de télémétrie en temps réel.",
    "portfolio.label": "05 / PORTFOLIO", "portfolio.title": "Réalisations",
    "portfolio.seq.badge1": "RH & PAIE", "portfolio.seq.badge2": "FLUTTER", "portfolio.seq.badge3": "VENTES", "portfolio.seq.num": "01 / FINTECH PHARE", "portfolio.seq.title": "SEQUIFI", "portfolio.seq.sub": "Gestion automatisée des commissions et paiements en temps réel", "portfolio.seq.desc": "Conçu pour les équipes commerciales dynamiques, SEQUIFI remplace les tableurs fragiles par le calcul automatisé des commissions et des classements motivants pour plus de 8 000 agents actifs.", "portfolio.seq.stat1v": "8 000+", "portfolio.seq.stat1l": "Agents actifs", "portfolio.seq.stat2v": "100%", "portfolio.seq.stat2l": "Mode hors ligne", "portfolio.seq.stat3v": "140M$+", "portfolio.seq.stat3l": "Flux de paie", "portfolio.seq.status": "Production V4.2.0 • Actif",
    "portfolio.fash.badge1": "MARKETPLACE MODE", "portfolio.fash.badge2": "FLUTTER", "portfolio.fash.badge3": "K-NET", "portfolio.fash.num": "02 // COMMERCE DE LUXE", "portfolio.fash.title": "FASH", "portfolio.fash.sub": "Ventes flash à fort trafic pour les boutiques de luxe au Koweït et aux É.A.U.", "portfolio.fash.desc": "Conçu pour les maisons de couture les plus exclusives de la région. FASH gère les pics de trafic extrêmes avec une file d'attente sans friction et la synchronisation des paiements multidevises K-NET.", "portfolio.fash.stat1v": "<2.1s", "portfolio.fash.stat1l": "Flux de paiement", "portfolio.fash.stat2v": "100k+", "portfolio.fash.stat2l": "Trafic de lancement", "portfolio.fash.stat3v": "4.9 ★", "portfolio.fash.stat3l": "Note App Store",
    "testimonials.label": "07 / VALIDATION", "testimonials.title": "Avis de nos clients",
    "testimonials.1.quote": "« Avenore n'agit pas comme un prestataire externe ; ils agissent comme une véritable équipe d'ingénierie. Ils ont livré notre application Flutter en 11 semaines, et notre taux de plantage en production est resté littéralement à zéro. »", "testimonials.1.name": "Marcus Vancamp", "testimonials.1.role": "CTO · PayGlide Systems",
    "testimonials.2.quote": "« Le niveau de conception des micro-interactions a complètement transformé la façon dont nos commerciaux utilisent le logiciel. Les commissions sont payées avec précision et la rétention a bondi de 32 % en 60 jours. »", "testimonials.2.name": "Priya Raman", "testimonials.2.role": "Directrice Produit · Sequifi",
    "whoWeAre.label": "08 / QUI SOMMES-NOUS", "whoWeAre.title": "Nous nous soucions de ce qui se passe après le lancement.", "whoWeAre.body": "Fondé sur le principe que le lancement n'est qu'un début. Nous livrons des applications robustes avec une disponibilité 24/7 et une expertise d'ingénierie exceptionnelle.",
    "whoWeAre.stat1v": "20+", "whoWeAre.stat1l": "Apps Lancées", "whoWeAre.stat2v": "100%", "whoWeAre.stat2l": "Précision Flutter", "whoWeAre.stat3v": "8+", "whoWeAre.stat3l": "Marchés Mondiaux", "whoWeAre.stat4v": "5+", "whoWeAre.stat4l": "Années d'expérience",
    "faq.label": "QUESTIONS", "faq.title": "Questions fréquentes",
    "inquiry.label": "DEMANDE DE PROJET", "inquiry.title": "Vous avez un projet ambitieux ?", "inquiry.body": "Parlons-en. Partagez votre calendrier, vos contraintes et vos ambitions. Nous répondons avec des estimations architecturales en moins de 24 heures.", "inquiry.cta": "Prendre un appel de découverte (15 min) →", "inquiry.check1": "NDA signé avant toute discussion confidentielle", "inquiry.check2": "Conversation directe avec un architecte produit",
    "footer.tagline": "NOUS CRÉONS DES PRODUITS AUXQUELS LES GENS REVIENNENT. Apps mobiles. Produits digitaux. Ingénierie rigoureuse.", "footer.location": "Koweït • Région CCG • Livraison mondiale", "footer.privacy": "Politique de confidentialité", "footer.terms": "Conditions d'utilisation", "footer.security": "Sécurité", "footer.rights": "© 2026 Avenore Studio. Tous droits réservés.",
    "services.label": "SERVICES", "services.title": "Ingénierie complète d'applications mobiles", "services.subtitle": "De Flutter à l'infrastructure cloud — nous construisons chaque couche.",
    "work.label": "PORTFOLIO", "work.title": "Études de cas en ingénierie", "work.subtitle": "Plateformes d'entreprise et places de marché digitales au Koweït et au CCG.", "work.viewAll": "Voir toutes les études de cas",
    "about.label": "À PROPOS", "about.title": "Nous construisons un produit, pas juste une app.", "about.subtitle": "Fondé au Koweït. Déploiement au CCG et à l'international.",
    "contact.label": "CONTACT", "contact.title": "Démarrez votre projet avec nous", "contact.subtitle": "Nous répondons à toutes les demandes sous 24 heures.",
    "common.readMore": "Lire la suite", "common.learnMore": "En savoir plus", "common.getInTouch": "Nous contacter", "common.viewCaseStudy": "Voir l'étude de cas"
  },
  es: {
    "nav.home": "Inicio", "nav.work": "Proyectos", "nav.services": "Servicios", "nav.about": "Nosotros", "nav.contact": "Contacto", "nav.startProject": "Iniciar Proyecto", "nav.bookCall": "Agendar llamada",
    "hero.badge": "Estudio fundado en 2026", "hero.location": "Apps Móviles Premium · Kuwait", "hero.headline": "Creamos productos a los que la gente regresa.", "hero.subheadline": "Apps móviles. Productos digitales. Ingeniería seria. Colaboramos con fundadores visionarios y empresas en el GCC y más allá.", "hero.cta.primary": "Iniciar Proyecto", "hero.cta.secondary": "Explorar Proyectos", "hero.proof": "Más de 20 apps en producción para FASH, Sequifi y MCC Dubai",
    "home.mockup.fash.studio": "ESTUDIO FASH", "home.mockup.fash.drop": "Drop Exclusivo #12", "home.mockup.fash.remaining": "124 PIEZAS DISPONIBLES", "home.mockup.fash.price": "125.000 KD", "home.mockup.fash.reserve": "RESERVAR",
    "home.mockup.mcc.badge": "MCC DUBAI · VERIFICADO", "home.mockup.mcc.status": "EN LÍNEA", "home.mockup.mcc.title": "Acceso UAE Pass", "home.mockup.mcc.token": "Token de Hardware Seguro", "home.mockup.mcc.session": "Sesión #99402 Autenticada", "home.mockup.mcc.monitoring": "Monitoreando 14 Sectores",
    "home.mockup.seq.badge": "SEQUIFI · COMISIONES", "home.mockup.seq.growth": "+18.4%", "home.mockup.seq.batch": "Lote de Pago #409", "home.mockup.seq.amount": "$84,200.00",
    "home.mockup.telemetry.badge": "TELEMETRÍA", "home.mockup.telemetry.uptime": "99.99%", "home.mockup.telemetry.flutter": "Motor Flutter", "home.mockup.telemetry.api": "Latencia API", "home.mockup.telemetry.cold": "Arranque en frío", "home.mockup.telemetry.fps": "FPS Render",
    "manifesto.label": "01 / LA IDEA", "manifesto.sectionTitle": "Filosofía del Estudio", "manifesto.headline": "Tu idea merece más que una simple app.", "manifesto.body": "Diseñamos productos digitales con arquitectura Flutter a prueba de balas, micro-interacciones obsesivas y confiabilidad en la nube. Sin plantillas subcontratadas ni capas de desarrolladores junior, solo ingenieros senior enviando productos que retienen usuarios y generan capital real.",
    "capabilities.label": "02 / CAPACIDADES", "capabilities.title": "Lo que construimos", "capabilities.subtitle": "Sistemas multiplataforma diseñados con precisión e infraestructura distribuida para soportar el mercado.",
    "capabilities.1.title": "Motores iOS y Android", "capabilities.1.desc": "Código Flutter de nivel de producción a 120 FPS. Sin compromisos híbridos.", "capabilities.1.badge": "COMPILACIÓN NATIVA",
    "capabilities.2.title": "Infraestructura Backend", "capabilities.2.desc": "PostgreSQL distribuido, WebSockets en tiempo real y arquitectura de cero inactividad.",
    "capabilities.3.title": "Ergonomía de Producto", "capabilities.3.desc": "Micro-animaciones táctiles e interfaces preparadas para RTL.",
    "capabilities.4.title": "Venture MVPs", "capabilities.4.desc": "Prototipos entregados en 8-12 semanas para asegurar rondas de inversión institucionales.",
    "capabilities.5.title": "Consolas Web", "capabilities.5.desc": "Flujos operativos unificados y dashboards de telemetría en tiempo real.",
    "portfolio.label": "05 / PORTAFOLIO", "portfolio.title": "Trabajos seleccionados",
    "portfolio.seq.badge1": "RRHH & NÓMINA", "portfolio.seq.badge2": "FLUTTER", "portfolio.seq.badge3": "VENTAS DE CAMPO", "portfolio.seq.num": "01 / FINTECH PRINCIPAL", "portfolio.seq.title": "SEQUIFI", "portfolio.seq.sub": "Gestión automatizada de comisiones y pagos en tiempo real", "portfolio.seq.desc": "Diseñado para equipos de ventas de alta velocidad, SEQUIFI reemplaza hojas de cálculo frágiles con cálculos de comisiones automatizados y tablas de clasificación para más de 8,000 representantes activos.", "portfolio.seq.stat1v": "8,000+", "portfolio.seq.stat1l": "Agentes Activos", "portfolio.seq.stat2v": "100%", "portfolio.seq.stat2l": "Modo Offline", "portfolio.seq.stat3v": "$140M+", "portfolio.seq.stat3l": "Flujo de Nómina", "portfolio.seq.status": "Producción V4.2.0 • Activo",
    "portfolio.fash.badge1": "MARKETPLACE MODA", "portfolio.fash.badge2": "FLUTTER", "portfolio.fash.badge3": "K-NET", "portfolio.fash.num": "02 // COMERCIO DE LUJO", "portfolio.fash.title": "FASH", "portfolio.fash.sub": "Lanzamientos de alta concurrencia para boutiques de lujo", "portfolio.fash.desc": "Diseñado para las casas de moda más exclusivas. FASH maneja ráfagas de tráfico extremo durante drops limitados con colas de pago sin fricción y sincronización K-NET.", "portfolio.fash.stat1v": "<2.1s", "portfolio.fash.stat1l": "Flujo de Pago", "portfolio.fash.stat2v": "100k+", "portfolio.fash.stat2l": "Tráfico de Drop", "portfolio.fash.stat3v": "4.9 ★", "portfolio.fash.stat3l": "Calificación App Store",
    "testimonials.label": "07 / VALIDACIÓN", "testimonials.title": "Perspectivas de clientes",
    "testimonials.1.quote": "«Avenore no actúa como un proveedor externo; actúan como un equipo de ingeniería incondicional. Entregaron nuestra aplicación Flutter en 11 semanas, y nuestra tasa de caídas en producción ha sido de cero.»", "testimonials.1.name": "Marcus Vancamp", "testimonials.1.role": "CTO · PayGlide Systems",
    "testimonials.2.quote": "«El nivel de micro-interacciones transformó por completo la forma en que nuestros representantes usan el software. Las comisiones se pagan correctamente y la retención saltó un 32% en 60 días.»", "testimonials.2.name": "Priya Raman", "testimonials.2.role": "Head de Producto · Sequifi",
    "whoWeAre.label": "08 / QUIÉNES SOMOS", "whoWeAre.title": "Nos importa lo que sucede después del lanzamiento.", "whoWeAre.body": "Fundado bajo el principio de que el lanzamiento es solo el inicio. Enviamos aplicaciones robustas con confiabilidad 24/7 y un diseño de ingeniería impecable.",
    "whoWeAre.stat1v": "20+", "whoWeAre.stat1l": "Apps Lanzadas", "whoWeAre.stat2v": "100%", "whoWeAre.stat2l": "Precisión Flutter", "whoWeAre.stat3v": "8+", "whoWeAre.stat3l": "Mercados Globales", "whoWeAre.stat4v": "5+", "whoWeAre.stat4l": "Años Experiencia",
    "faq.label": "PREGUNTAS", "faq.title": "Preguntas Frecuentes",
    "inquiry.label": "CONSULTA DE PROYECTO", "inquiry.title": "¿Tienes algo que valga la pena construir?", "inquiry.body": "Hablemos de ello. Cuéntanos sobre tu cronograma y objetivos. Respondemos con estimaciones arquitectónicas en menos de 24 horas.", "inquiry.cta": "Agendar llamada de descubrimiento (15 min) →", "inquiry.check1": "NDA firmado antes de discusiones confidenciales", "inquiry.check2": "Conversación directa con el arquitecto principal",
    "footer.tagline": "CREAMOS PRODUCTOS A LOS QUE LA GENTE REGRESA. Apps móviles. Productos digitales. Ingeniería seria.", "footer.location": "Kuwait • Región GCC • Entrega Global", "footer.privacy": "Política de Privacidad", "footer.terms": "Términos de Servicio", "footer.security": "Seguridad", "footer.rights": "© 2026 Avenore Studio. Todos los derechos reservados.",
    "services.label": "SERVICIOS", "services.title": "Ingeniería Completa de Apps Móviles", "services.subtitle": "Desde Flutter hasta infraestructura en la nube — construimos cada capa.",
    "work.label": "PORTAFOLIO", "work.title": "Casos de Estudio de Ingeniería", "work.subtitle": "Marketplaces digitales y plataformas empresariales en todo Kuwait y el GCC.", "work.viewAll": "Ver todos los Casos de Estudio",
    "about.label": "NOSOTROS", "about.title": "Diseñamos un producto, no solo una app.", "about.subtitle": "Fundado en Kuwait. Envíos en todo el GCC y más allá.",
    "contact.label": "CONTACTO", "contact.title": "Inicia tu proyecto con nosotros", "contact.subtitle": "Respondemos a todas las consultas en menos de 24 horas.",
    "common.readMore": "Leer más", "common.learnMore": "Conocer más", "common.getInTouch": "Contáctanos", "common.viewCaseStudy": "Ver Caso de Estudio"
  },
  zh: {
    "nav.home": "首页", "nav.work": "案例", "nav.services": "服务", "nav.about": "关于", "nav.contact": "联系", "nav.startProject": "启动项目", "nav.bookCall": "预约会议",
    "hero.badge": "成立于 2026 年", "hero.location": "高端移动应用开发 · 科威特", "hero.headline": "打造用户信赖与回归的顶级产品。", "hero.subheadline": "移动应用、数字产品、专业工程开发。我们与海湾地区及全球的远见创始人与企业团队合作。", "hero.cta.primary": "启动项目", "hero.cta.secondary": "浏览精选案例", "hero.proof": "已为 FASH、Sequifi 和 MCC Dubai 交付 20+ 款生产级应用",
    "home.mockup.fash.studio": "FASH 工作室", "home.mockup.fash.drop": "精选限量版 #12", "home.mockup.fash.remaining": "仅剩 124 件", "home.mockup.fash.price": "125.000 KD", "home.mockup.fash.reserve": "立即预订",
    "home.mockup.mcc.badge": "MCC DUBAI · 认证", "home.mockup.mcc.status": "在线", "home.mockup.mcc.title": "UAE Pass 访问", "home.mockup.mcc.token": "安全硬件令牌", "home.mockup.mcc.session": "会话 #99402 已认证", "home.mockup.mcc.monitoring": "监控 14 个部门",
    "home.mockup.seq.badge": "SEQUIFI · 佣金系统", "home.mockup.seq.growth": "+18.4%", "home.mockup.seq.batch": "支付批次 #409", "home.mockup.seq.amount": "$84,200.00",
    "home.mockup.telemetry.badge": "核心遥测", "home.mockup.telemetry.uptime": "99.99%", "home.mockup.telemetry.flutter": "Flutter 引擎", "home.mockup.telemetry.api": "API 延迟", "home.mockup.telemetry.cold": "冷启动时间", "home.mockup.telemetry.fps": "帧率 (FPS)",
    "manifesto.label": "01 / 理念", "manifesto.sectionTitle": "我们的哲学", "manifesto.headline": "您的创意值得拥有一流的工程实现。", "manifesto.body": "我们采用坚如磐石的 Flutter 架构、极致的微交互设计和企业级云基础设施来打造持久的数字产品。没有外包模板，没有冗余的初级代码——只有资深工程师为您交付能留住用户并产生实际资本回报的产品。",
    "capabilities.label": "02 / 核心能力", "capabilities.title": "我们的专长", "capabilities.subtitle": "精准打造跨平台系统、定制移动生态及能够抵御市场波动的分布式基础设施。",
    "capabilities.1.title": "iOS 与 Android 引擎", "capabilities.1.desc": "生产级 Flutter 代码库，稳定输出 120 FPS 的流畅物理效果，绝无混合应用的妥协。", "capabilities.1.badge": "原生编译",
    "capabilities.2.title": "后端基础设施", "capabilities.2.desc": "分布式 PostgreSQL 数据库、实时 WebSockets，以及符合海湾地区标准的零停机架构。",
    "capabilities.3.title": "产品体验工程", "capabilities.3.desc": "极致丝滑的触觉微动画以及完美支持 RTL 的移动界面。",
    "capabilities.4.title": "初创期 MVP 交付", "capabilities.4.desc": "在 8–12 周内交付高质量原型，助力获取机构种子轮融资。",
    "capabilities.5.title": "Web 管理控制台", "capabilities.5.desc": "统一的操作工作流与实时商户遥测数据看板。",
    "portfolio.label": "05 / 作品集", "portfolio.title": "精选案例",
    "portfolio.seq.badge1": "人力资源与薪酬", "portfolio.seq.badge2": "FLUTTER", "portfolio.seq.badge3": "现场销售", "portfolio.seq.num": "01 / 金融科技旗舰项目", "portfolio.seq.title": "SEQUIFI", "portfolio.seq.sub": "实时自动化佣金管理与员工结算系统", "portfolio.seq.desc": "专为高频现场销售团队设计，SEQUIFI 替代了脆弱的表格工具，为超 8,000 名活跃销售人员提供自动化佣金计算和支付验证。", "portfolio.seq.stat1v": "8,000+", "portfolio.seq.stat1l": "活跃代表", "portfolio.seq.stat2v": "100%", "portfolio.seq.stat2l": "支持离线", "portfolio.seq.stat3v": "$140M+", "portfolio.seq.stat3l": "结算流水", "portfolio.seq.status": "V4.2.0 生产环境 • 运行中",
    "portfolio.fash.badge1": "时尚电商平台", "portfolio.fash.badge2": "FLUTTER", "portfolio.fash.badge3": "K-NET 支付", "portfolio.fash.num": "02 // 奢侈品电商", "portfolio.fash.title": "FASH", "portfolio.fash.sub": "科威特与阿联酋奢侈品精品店的高并发抢购系统", "portfolio.fash.desc": "专为本地区最顶尖的时尚品牌量身定制。FASH 在限量发售期间处理极端爆发流量，具备无缝结账队列及多货币 K-NET 支付同步功能。", "portfolio.fash.stat1v": "<2.1s", "portfolio.fash.stat1l": "结账耗时", "portfolio.fash.stat2v": "100k+", "portfolio.fash.stat2l": "抢购流量", "portfolio.fash.stat3v": "4.9 ★", "portfolio.fash.stat3l": "应用商店评分",
    "testimonials.label": "07 / 客户验证", "testimonials.title": "客户评价",
    "testimonials.1.quote": "“Avenore 不像一个外部供应商，他们就像我们自己毫不妥协的核心工程团队。他们仅在11周内就交付了完整的 Flutter 应用，而在生产环境中的崩溃率依然保持在零。”", "testimonials.1.name": "Marcus Vancamp", "testimonials.1.role": "CTO · PayGlide Systems",
    "testimonials.2.quote": "“他们为 Sequifi 带来的微交互与手势设计水平，彻底改变了现场代表使用软件的方式。佣金发放更加准确，发布后60天内留存率跃升了 32%。”", "testimonials.2.name": "Priya Raman", "testimonials.2.role": "产品负责人 · Sequifi",
    "whoWeAre.label": "08 / 关于我们", "whoWeAre.title": "发布上线仅仅是开始。", "whoWeAre.body": "我们秉持“上线即起跑线”的原则。我们交付的高可用性应用具备 24/7 站点可靠性和极致的工程水准。",
    "whoWeAre.stat1v": "20+", "whoWeAre.stat1l": "已交付应用", "whoWeAre.stat2v": "100%", "whoWeAre.stat2l": "Flutter 原生体验", "whoWeAre.stat3v": "8+", "whoWeAre.stat3l": "全球覆盖市场", "whoWeAre.stat4v": "5+", "whoWeAre.stat4l": "年行业经验",
    "faq.label": "疑问解答", "faq.title": "常见问题",
    "inquiry.label": "项目咨询", "inquiry.title": "准备好构建下一代产品了吗？", "inquiry.body": "让我们详细沟通。告诉我们您的时间表、产品需求和市场雄心。我们将在 24 小时内提供专业的架构评估。", "inquiry.cta": "预约 15 分钟快速探索会议 →", "inquiry.check1": "保密协议 (NDA) 签署保障", "inquiry.check2": "首席产品架构师一对一深度沟通",
    "footer.tagline": "打造用户信赖与回归的顶级产品。移动应用、数字产品、专业工程。", "footer.location": "科威特城 • 海湾合作委员会地区 • 交付全球", "footer.privacy": "隐私政策", "footer.terms": "服务条款", "footer.security": "安全说明", "footer.rights": "© 2026 Avenore Studio. 保留所有权利。",
    "services.label": "服务项目", "services.title": "全栈移动应用工程开发", "services.subtitle": "从 Flutter 客户端到后端云基础设施 — 每一层代码均由我们精心构建。",
    "work.label": "作品集", "work.title": "精选案例与技术深度解析", "work.subtitle": "助力科威特及海湾地区的顶级企业与初创公司打造旗舰级移动数字产品。", "work.viewAll": "查看所有案例",
    "about.label": "关于我们", "about.title": "我们不仅做应用，更在创造产品。", "about.subtitle": "总部位于科威特，放眼全球市场。",
    "contact.label": "联系我们", "contact.title": "开启您的项目合作", "contact.subtitle": "我们承诺在 24 小时内回复所有咨询。",
    "common.readMore": "阅读更多", "common.learnMore": "了解详情", "common.getInTouch": "联系我们", "common.viewCaseStudy": "查看案例分析"
  },
  ja: {
    "nav.home": "ホーム", "nav.work": "制作実績", "nav.services": "サービス", "nav.about": "私たちについて", "nav.contact": "お問い合わせ", "nav.startProject": "プロジェクト開始", "nav.bookCall": "ミーティング予約",
    "hero.badge": "設立 2026年", "hero.location": "プレミアムモバイルアプリ · クウェート", "hero.headline": "人々が戻ってくるプロダクトを構築します。", "hero.subheadline": "モバイルアプリ、デジタル製品、本格的なエンジニアリング。私たちはGCCや世界中のビジョナリーな創業者と提携しています。", "hero.cta.primary": "プロジェクトを開始", "hero.cta.secondary": "実績を探索", "hero.proof": "FASH、Sequifi、MCC Dubai向けに20以上の本番アプリを提供",
    "home.mockup.fash.studio": "FASH スタジオ", "home.mockup.fash.drop": "限定ドロップ #12", "home.mockup.fash.remaining": "残り 124 点", "home.mockup.fash.price": "125.000 KD", "home.mockup.fash.reserve": "予約する",
    "home.mockup.mcc.badge": "MCC DUBAI · 認証済み", "home.mockup.mcc.status": "オンライン", "home.mockup.mcc.title": "UAE Pass アクセス", "home.mockup.mcc.token": "セキュアハードウェアトークン", "home.mockup.mcc.session": "セッション #99402 認証済み", "home.mockup.mcc.monitoring": "14セクターを監視中",
    "home.mockup.seq.badge": "SEQUIFI · 手数料", "home.mockup.seq.growth": "+18.4%", "home.mockup.seq.batch": "支払いバッチ #409", "home.mockup.seq.amount": "$84,200.00",
    "home.mockup.telemetry.badge": "コアテレメトリ", "home.mockup.telemetry.uptime": "99.99%", "home.mockup.telemetry.flutter": "Flutter エンジン", "home.mockup.telemetry.api": "API レイテンシ", "home.mockup.telemetry.cold": "コールドスタート", "home.mockup.telemetry.fps": "フレームレート(FPS)",
    "manifesto.label": "01 / アイデア", "manifesto.sectionTitle": "スタジオの哲学", "manifesto.headline": "あなたのアイデアは、単なるアプリ以上の価値があります。", "manifesto.body": "堅牢なFlutterアーキテクチャ、緻密なマイクロインタラクション、そしてエンタープライズ品質のクラウド信頼性を備えたデジタル製品をエンジニアリングします。アウトソーシングのテンプレートは使用しません。",
    "capabilities.label": "02 / ケイパビリティ", "capabilities.title": "私たちが構築するもの", "capabilities.subtitle": "市場の変化に耐えうる、クロスプラットフォームシステムと分散型インフラストラクチャ。",
    "capabilities.1.title": "iOS & Android エンジン", "capabilities.1.desc": "120FPSの滑らかな物理動作を出力するプロダクションレベルのFlutterコード。妥協はありません。", "capabilities.1.badge": "ネイティブコンパイル",
    "capabilities.2.title": "バックエンドインフラ", "capabilities.2.desc": "分散型PostgreSQL、リアルタイムWebSockets、ゼロダウンタイムのアーキテクチャ。",
    "capabilities.3.title": "製品エルゴノミクス", "capabilities.3.desc": "触覚的なマイクロアニメーションとRTL対応のモバイルインターフェース。",
    "capabilities.4.title": "ベンチャー MVP", "capabilities.4.desc": "シード資金を確保するため、8〜12週間で妥協のないプロトタイプを提供します。",
    "capabilities.5.title": "Web コンソール", "capabilities.5.desc": "統合されたオペレーションワークフローとリアルタイムのダッシュボード。",
    "portfolio.label": "05 / ポートフォリオ", "portfolio.title": "厳選された実績",
    "portfolio.seq.badge1": "人事・給与", "portfolio.seq.badge2": "FLUTTER", "portfolio.seq.badge3": "フィールドセールス", "portfolio.seq.num": "01 / フィンテック旗艦", "portfolio.seq.title": "SEQUIFI", "portfolio.seq.sub": "リアルタイムの自動コミッション管理", "portfolio.seq.desc": "高速なセールスチーム向けに設計されたSEQUIFIは、脆弱なスプレッドシートを自動化されたシステムに置き換えます。", "portfolio.seq.stat1v": "8,000+", "portfolio.seq.stat1l": "アクティブな営業担当", "portfolio.seq.stat2v": "100%", "portfolio.seq.stat2l": "オフライン対応", "portfolio.seq.stat3v": "$140M+", "portfolio.seq.stat3l": "給与フロー", "portfolio.seq.status": "本番 V4.2.0 • 稼働中",
    "portfolio.fash.badge1": "ファッション市場", "portfolio.fash.badge2": "FLUTTER", "portfolio.fash.badge3": "K-NET", "portfolio.fash.num": "02 // ラグジュアリーコマース", "portfolio.fash.title": "FASH", "portfolio.fash.sub": "クウェートの高級ブティック向け高同時接続ドロップ", "portfolio.fash.desc": "地域の最も厳選されたファッションハウス向けにカスタマイズ。フラッシュドロップ中の極端なトラフィックを処理します。", "portfolio.fash.stat1v": "<2.1s", "portfolio.fash.stat1l": "チェックアウト", "portfolio.fash.stat2v": "100k+", "portfolio.fash.stat2l": "ドロップトラフィック", "portfolio.fash.stat3v": "4.9 ★", "portfolio.fash.stat3l": "ストア評価",
    "testimonials.label": "07 / 顧客の声", "testimonials.title": "クライアントの視点",
    "testimonials.1.quote": "「Avenoreは外部ベンダーのようにではなく、妥協のない中核的なエンジニアリングチームとして行動します。Flutterアプリを11週間で完成させました。」", "testimonials.1.name": "Marcus Vancamp", "testimonials.1.role": "CTO · PayGlide Systems",
    "testimonials.2.quote": "「彼らがSequifiにもたらしたマイクロインタラクションのデザインは、営業担当のソフトウェア使用方法を完全に変えました。」", "testimonials.2.name": "Priya Raman", "testimonials.2.role": "製品責任者 · Sequifi",
    "whoWeAre.label": "08 / 私たちについて", "whoWeAre.title": "リリース後を見据えた開発。", "whoWeAre.body": "リリース日はスタートラインに過ぎないという原則に基づいています。24時間365日の信頼性を持つアプリを提供します。",
    "whoWeAre.stat1v": "20+", "whoWeAre.stat1l": "リリース済みアプリ", "whoWeAre.stat2v": "100%", "whoWeAre.stat2l": "Flutterの精度", "whoWeAre.stat3v": "8+", "whoWeAre.stat3l": "グローバル市場", "whoWeAre.stat4v": "5+", "whoWeAre.stat4l": "年の経験",
    "faq.label": "お問い合わせ", "faq.title": "よくある質問",
    "inquiry.label": "プロジェクトの相談", "inquiry.title": "構築する価値のあるものがありますか？", "inquiry.body": "タイムラインや市場の野望についてお聞かせください。24時間以内にアーキテクチャの見積もりを回答します。", "inquiry.cta": "15分のクイックコールを予約 →", "inquiry.check1": "機密プロジェクトの議論前のNDA署名", "inquiry.check2": "リードアーキテクトとの直接対話",
    "footer.tagline": "人々が戻ってくる製品を構築します。モバイルアプリ、デジタル製品。", "footer.location": "クウェート市 • GCC地域 • グローバルデリバリー", "footer.privacy": "プライバシーポリシー", "footer.terms": "利用規約", "footer.security": "セキュリティ", "footer.rights": "© 2026 Avenore Studio. 全著作権所有。",
    "services.label": "サービス", "services.title": "フルスタック モバイルアプリ エンジニアリング", "services.subtitle": "Flutterからクラウドまで、すべてのレイヤーを構築します。",
    "work.label": "ポートフォリオ", "work.title": "厳選された実績とケーススタディ", "work.subtitle": "GCC全域のエンタープライズプラットフォームとデジタル市場。", "work.viewAll": "すべてのケーススタディを見る",
    "about.label": "私たちについて", "about.title": "単なるアプリではなく、製品をエンジニアリングします。", "about.subtitle": "クウェートで設立され、世界中に展開しています。",
    "contact.label": "お問い合わせ", "contact.title": "プロジェクトを開始", "contact.subtitle": "24時間以内にお問い合わせに返信します。",
    "common.readMore": "続きを読む", "common.learnMore": "さらに詳しく", "common.getInTouch": "連絡を取る", "common.viewCaseStudy": "ケーススタディを見る"
  },
  ru: {
    "nav.home": "Главная", "nav.work": "Проекты", "nav.services": "Услуги", "nav.about": "О нас", "nav.contact": "Контакты", "nav.startProject": "Начать проект", "nav.bookCall": "Заказать звонок",
    "hero.badge": "Студия осн. в 2026", "hero.location": "Премиум мобильные приложения · Кувейт", "hero.headline": "Мы создаем продукты, к которым возвращаются.", "hero.subheadline": "Мобильные приложения. Цифровые продукты. Серьезная инженерия. Мы сотрудничаем с визионерами и корпоративными командами на Ближнем Востоке и за его пределами.", "hero.cta.primary": "Начать проект", "hero.cta.secondary": "Наши работы", "hero.proof": "Более 20 успешных приложений для FASH, Sequifi и MCC Dubai",
    "home.mockup.fash.studio": "FASH СТУДИЯ", "home.mockup.fash.drop": "Эксклюзивный дроп #12", "home.mockup.fash.remaining": "ОСТАЛОСЬ 124 ШТ", "home.mockup.fash.price": "125.000 KD", "home.mockup.fash.reserve": "ЗАБРОНИРОВАТЬ",
    "home.mockup.mcc.badge": "MCC DUBAI · ВЕРИФИЦИРОВАНО", "home.mockup.mcc.status": "ОНЛАЙН", "home.mockup.mcc.title": "Доступ UAE Pass", "home.mockup.mcc.token": "Аппаратный токен", "home.mockup.mcc.session": "Сессия #99402 Аутентифицирована", "home.mockup.mcc.monitoring": "Мониторинг 14 секторов",
    "home.mockup.seq.badge": "SEQUIFI · КОМИССИИ", "home.mockup.seq.growth": "+18.4%", "home.mockup.seq.batch": "Выплата #409", "home.mockup.seq.amount": "$84,200.00",
    "home.mockup.telemetry.badge": "ТЕЛЕМЕТРИЯ", "home.mockup.telemetry.uptime": "99.99%", "home.mockup.telemetry.flutter": "Движок Flutter", "home.mockup.telemetry.api": "API Задержка", "home.mockup.telemetry.cold": "Холодный старт", "home.mockup.telemetry.fps": "Рендер FPS",
    "manifesto.label": "01 / ИДЕЯ", "manifesto.sectionTitle": "Философия студии", "manifesto.headline": "Ваша идея заслуживает большего, чем просто приложение.", "manifesto.body": "Мы проектируем долговечные цифровые продукты с пуленепробиваемой архитектурой Flutter, безупречными микро-взаимодействиями и корпоративной надежностью облачной инфраструктуры.",
    "capabilities.label": "02 / ВОЗМОЖНОСТИ", "capabilities.title": "Что мы создаем", "capabilities.subtitle": "Кроссплатформенные системы, экосистемы мобильных приложений и распределенная инфраструктура.",
    "capabilities.1.title": "Движки iOS и Android", "capabilities.1.desc": "Продакшн-код Flutter с частотой 120 FPS. Никаких гибридных компромиссов.", "capabilities.1.badge": "НАТИВНАЯ КОМПИЛЯЦИЯ",
    "capabilities.2.title": "Бэкенд Инфраструктура", "capabilities.2.desc": "Распределенная PostgreSQL, WebSockets в реальном времени и архитектура без простоев.",
    "capabilities.3.title": "Эргономика продуктов", "capabilities.3.desc": "Тактильные микро-анимации и интерфейсы с поддержкой RTL.",
    "capabilities.4.title": "Venture MVP", "capabilities.4.desc": "Прототипы за 8–12 недель для обеспечения посевного финансирования.",
    "capabilities.5.title": "Веб-консоли", "capabilities.5.desc": "Унифицированные рабочие процессы и панели телеметрии в реальном времени.",
    "portfolio.label": "05 / ПОРТФОЛИО", "portfolio.title": "Избранные работы",
    "portfolio.seq.badge1": "HR И ЗАРПЛАТА", "portfolio.seq.badge2": "FLUTTER", "portfolio.seq.badge3": "ПРОДАЖИ", "portfolio.seq.num": "01 / ФИНТЕХ ПРОЕКТ", "portfolio.seq.title": "SEQUIFI", "portfolio.seq.sub": "Автоматизированное управление комиссиями в реальном времени", "portfolio.seq.desc": "Разработано для высокоскоростных команд. SEQUIFI заменяет хрупкие таблицы автоматическим расчетом комиссий.", "portfolio.seq.stat1v": "8,000+", "portfolio.seq.stat1l": "Активных агентов", "portfolio.seq.stat2v": "100%", "portfolio.seq.stat2l": "Офлайн-режим", "portfolio.seq.stat3v": "$140M+", "portfolio.seq.stat3l": "Объем выплат", "portfolio.seq.status": "Продакшн V4.2.0 • Активен",
    "portfolio.fash.badge1": "FASHION МАРКЕТПЛЕЙС", "portfolio.fash.badge2": "FLUTTER", "portfolio.fash.badge3": "K-NET", "portfolio.fash.num": "02 // ЛЮКС КОММЕРЦИЯ", "portfolio.fash.title": "FASH", "portfolio.fash.sub": "Релиз с высокой нагрузкой для люксовых бутиков", "portfolio.fash.desc": "Адаптировано для самых эксклюзивных домов моды. FASH справляется с экстремальным трафиком без проблем с очередями оплаты.", "portfolio.fash.stat1v": "<2.1s", "portfolio.fash.stat1l": "Время чекаута", "portfolio.fash.stat2v": "100k+", "portfolio.fash.stat2l": "Трафик при дропе", "portfolio.fash.stat3v": "4.9 ★", "portfolio.fash.stat3l": "Оценка в магазине",
    "testimonials.label": "07 / ВАЛИДАЦИЯ", "testimonials.title": "Мнения клиентов",
    "testimonials.1.quote": "«Avenore действует не как внешний вендор, а как бескомпромиссная команда инженеров. Они доставили приложение Flutter всего за 11 недель.»", "testimonials.1.name": "Маркус Ванкамп", "testimonials.1.role": "CTO · PayGlide Systems",
    "testimonials.2.quote": "«Уровень дизайна микро-взаимодействий полностью изменил то, как наши представители используют софт.»", "testimonials.2.name": "Прия Раман", "testimonials.2.role": "Руководитель продукта · Sequifi",
    "whoWeAre.label": "08 / О НАС", "whoWeAre.title": "Нам важно, что будет после запуска.", "whoWeAre.body": "Мы верим, что запуск — это только начало. Мы поставляем надежные приложения с бесперебойной работой 24/7.",
    "whoWeAre.stat1v": "20+", "whoWeAre.stat1l": "Приложений", "whoWeAre.stat2v": "100%", "whoWeAre.stat2l": "Точность Flutter", "whoWeAre.stat3v": "8+", "whoWeAre.stat3l": "Мировых рынков", "whoWeAre.stat4v": "5+", "whoWeAre.stat4l": "Лет опыта",
    "faq.label": "ВОПРОСЫ", "faq.title": "Часто задаваемые вопросы",
    "inquiry.label": "ЗАПРОС ПРОЕКТА", "inquiry.title": "Есть отличная идея?", "inquiry.body": "Расскажите нам о ваших сроках, ограничениях продукта и амбициях. Мы ответим оценкой архитектуры менее чем за 24 часа.", "inquiry.cta": "Заказать 15-мин звонок →", "inquiry.check1": "NDA перед обсуждением", "inquiry.check2": "Прямой разговор с главным архитектором",
    "footer.tagline": "МЫ СОЗДАЕМ ПРОДУКТЫ, К КОТОРЫМ ВОЗВРАЩАЮТСЯ.", "footer.location": "Кувейт • Ближний Восток • Доставка по миру", "footer.privacy": "Политика конфиденциальности", "footer.terms": "Условия", "footer.security": "Безопасность", "footer.rights": "© 2026 Avenore Studio. Все права защищены.",
    "services.label": "УСЛУГИ", "services.title": "Full-Stack Инженерия Мобильных Приложений", "services.subtitle": "От Flutter до облачной инфраструктуры.",
    "work.label": "ПОРТФОЛИО", "work.title": "Избранные работы", "work.subtitle": "Корпоративные платформы и цифровые маркетплейсы.", "work.viewAll": "Смотреть все кейсы",
    "about.label": "О НАС", "about.title": "Мы проектируем продукт, а не просто приложение.", "about.subtitle": "Основано в Кувейте. Работаем по всему миру.",
    "contact.label": "КОНТАКТЫ", "contact.title": "Начните проект с нами", "contact.subtitle": "Мы отвечаем на все запросы в течение 24 часов.",
    "common.readMore": "Читать далее", "common.learnMore": "Узнать больше", "common.getInTouch": "Связаться с нами", "common.viewCaseStudy": "Посмотреть кейс"
  },
  pt: {
    "nav.home": "Início", "nav.work": "Trabalhos", "nav.services": "Serviços", "nav.about": "Sobre nós", "nav.contact": "Contato", "nav.startProject": "Iniciar Projeto", "nav.bookCall": "Agendar chamada",
    "hero.badge": "Estúdio Fundado em 2026", "hero.location": "Apps Móveis Premium · Kuwait", "hero.headline": "Criamos produtos aos quais as pessoas voltam.", "hero.subheadline": "Apps móveis. Produtos digitais. Engenharia séria. Somos parceiros de fundadores visionários no GCC e além.", "hero.cta.primary": "Iniciar Projeto", "hero.cta.secondary": "Explorar Trabalhos", "hero.proof": "Mais de 20 apps em produção para FASH, Sequifi e MCC Dubai",
    "home.mockup.fash.studio": "ESTÚDIO FASH", "home.mockup.fash.drop": "Drop Exclusivo #12", "home.mockup.fash.remaining": "124 PEÇAS RESTANTES", "home.mockup.fash.price": "125.000 KD", "home.mockup.fash.reserve": "RESERVAR",
    "home.mockup.mcc.badge": "MCC DUBAI · VERIFICADO", "home.mockup.mcc.status": "ONLINE", "home.mockup.mcc.title": "Acesso UAE Pass", "home.mockup.mcc.token": "Token de Hardware Seguro", "home.mockup.mcc.session": "Sessão #99402 Autenticada", "home.mockup.mcc.monitoring": "Monitorando 14 Setores",
    "home.mockup.seq.badge": "SEQUIFI · COMISSÕES", "home.mockup.seq.growth": "+18.4%", "home.mockup.seq.batch": "Lote de Pagamento #409", "home.mockup.seq.amount": "$84.200,00",
    "home.mockup.telemetry.badge": "TELEMETRIA", "home.mockup.telemetry.uptime": "99.99%", "home.mockup.telemetry.flutter": "Motor Flutter", "home.mockup.telemetry.api": "Latência API", "home.mockup.telemetry.cold": "Arranque a frio", "home.mockup.telemetry.fps": "FPS Render",
    "manifesto.label": "01 / A IDEIA", "manifesto.sectionTitle": "Filosofia do Estúdio", "manifesto.headline": "Sua ideia merece mais do que um simples app.", "manifesto.body": "Nós projetamos produtos digitais duráveis com arquitetura Flutter impecável, micro-interações obsessivas e confiabilidade de infraestrutura corporativa.",
    "capabilities.label": "02 / CAPACIDADES", "capabilities.title": "O que construímos", "capabilities.subtitle": "Sistemas multiplataforma criados sob medida e ecossistemas móveis.",
    "capabilities.1.title": "Motores iOS & Android", "capabilities.1.desc": "Código Flutter em nível de produção entregando 120 FPS. Sem atalhos híbridos.", "capabilities.1.badge": "COMPILAÇÃO NATIVA",
    "capabilities.2.title": "Infraestrutura Backend", "capabilities.2.desc": "PostgreSQL distribuído, WebSockets em tempo real e arquitetura sem inatividade.",
    "capabilities.3.title": "Ergonomia do Produto", "capabilities.3.desc": "Micro-animações táteis e interfaces móveis compatíveis com RTL.",
    "capabilities.4.title": "Venture MVPs", "capabilities.4.desc": "Protótipos entregues em 8 a 12 semanas para garantir rodadas de investimento.",
    "capabilities.5.title": "Consoles Web", "capabilities.5.desc": "Fluxos de trabalho unificados e painéis de telemetria para lojistas.",
    "portfolio.label": "05 / PORTFÓLIO", "portfolio.title": "Trabalhos selecionados",
    "portfolio.seq.badge1": "RH & FOLHA", "portfolio.seq.badge2": "FLUTTER", "portfolio.seq.badge3": "VENDAS", "portfolio.seq.num": "01 / FINTECH LÍDER", "portfolio.seq.title": "SEQUIFI", "portfolio.seq.sub": "Gestão de comissões automatizada em tempo real", "portfolio.seq.desc": "Construído para equipes de alta velocidade, SEQUIFI substitui planilhas frágeis por cálculos de comissões automatizados.", "portfolio.seq.stat1v": "8.000+", "portfolio.seq.stat1l": "Representantes Ativos", "portfolio.seq.stat2v": "100%", "portfolio.seq.stat2l": "Modo Offline", "portfolio.seq.stat3v": "$140M+", "portfolio.seq.stat3l": "Volume de Pagamentos", "portfolio.seq.status": "Produção V4.2.0 • Ativo",
    "portfolio.fash.badge1": "MARKETPLACE MODA", "portfolio.fash.badge2": "FLUTTER", "portfolio.fash.badge3": "K-NET", "portfolio.fash.num": "02 // COMÉRCIO DE LUXO", "portfolio.fash.title": "FASH", "portfolio.fash.sub": "Vendas de alto volume para boutiques de luxo", "portfolio.fash.desc": "FASH lida com picos extremos de tráfego durante eventos limitados, com fila de checkout sem fricção e sincronização K-NET.", "portfolio.fash.stat1v": "<2.1s", "portfolio.fash.stat1l": "Fluxo de Checkout", "portfolio.fash.stat2v": "100k+", "portfolio.fash.stat2l": "Tráfego no Lançamento", "portfolio.fash.stat3v": "4.9 ★", "portfolio.fash.stat3l": "Nota na App Store",
    "testimonials.label": "07 / VALIDAÇÃO", "testimonials.title": "Perspectivas de Clientes",
    "testimonials.1.quote": "«Avenore não atua como fornecedor; eles são nossa equipe central de engenharia. Entregaram nosso app Flutter em apenas 11 semanas, sem falhas de produção.»", "testimonials.1.name": "Marcus Vancamp", "testimonials.1.role": "CTO · PayGlide Systems",
    "testimonials.2.quote": "«O nível de micro-interações transformou a maneira como nossos representantes usam o software. As comissões são exatas e a retenção saltou 32%.»", "testimonials.2.name": "Priya Raman", "testimonials.2.role": "Head de Produto · Sequifi",
    "whoWeAre.label": "08 / QUEM SOMOS", "whoWeAre.title": "Nos importamos com o que vem após o lançamento.", "whoWeAre.body": "O lançamento é apenas o começo. Entregamos aplicativos robustos e operacionais 24/7.",
    "whoWeAre.stat1v": "20+", "whoWeAre.stat1l": "Apps Lançados", "whoWeAre.stat2v": "100%", "whoWeAre.stat2l": "Precisão Flutter", "whoWeAre.stat3v": "8+", "whoWeAre.stat3l": "Mercados Globais", "whoWeAre.stat4v": "5+", "whoWeAre.stat4l": "Anos de Experiência",
    "faq.label": "DÚVIDAS", "faq.title": "Perguntas Frequentes",
    "inquiry.label": "CONSULTA DE PROJETO", "inquiry.title": "Tem um projeto incrível em mente?", "inquiry.body": "Conte-nos sobre seus prazos e objetivos. Respondemos com uma estimativa em menos de 24 horas.", "inquiry.cta": "Agendar chamada rápida de 15min →", "inquiry.check1": "NDA assinado antes de conversas confidenciais", "inquiry.check2": "Conversa direta com o Arquiteto Líder",
    "footer.tagline": "CRIAMOS PRODUTOS AOS QUAIS AS PESSOAS VOLTAM.", "footer.location": "Kuwait • GCC • Atendimento Global", "footer.privacy": "Política de Privacidade", "footer.terms": "Termos de Serviço", "footer.security": "Segurança", "footer.rights": "© 2026 Avenore Studio. Todos os direitos reservados.",
    "services.label": "SERVIÇOS", "services.title": "Engenharia Full-Stack Mobile", "services.subtitle": "Do Flutter à nuvem — nós construímos cada etapa.",
    "work.label": "PORTFÓLIO", "work.title": "Trabalhos Selecionados", "work.subtitle": "Marketplaces digitais e plataformas empresariais.", "work.viewAll": "Ver todos os Casos de Sucesso",
    "about.label": "SOBRE", "about.title": "Engenhamos um produto, não apenas um app.", "about.subtitle": "Fundado no Kuwait. Exportando para o GCC e o mundo.",
    "contact.label": "CONTATO", "contact.title": "Inicie o seu projeto conosco", "contact.subtitle": "Respondemos a todas as dúvidas em até 24h.",
    "common.readMore": "Ler Mais", "common.learnMore": "Saber Mais", "common.getInTouch": "Fale Conosco", "common.viewCaseStudy": "Ver Caso"
  }
};
